(function(){
'use strict';var d,aa=Object.freeze({assumingES6:!1,productionMode:!0,linkerVersion:"1.0.1",fileLevelThis:this}),ba=Object.is||function(a,b){return a===b?0!==a||1/a===1/b:a!==a&&b!==b},l=Math.imul||function(a,b){var c=a&65535,e=b&65535;return c*e+((a>>>16)*e+c*(b>>>16)<<16>>>0)|0},ca=Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&-65536)&&(a<<=16,b+=16);0===(a&-16777216)&&(a<<=8,b+=8);0===(a&-268435456)&&(a<<=4,b+=4);0===(a&-1073741824)&&(a<<=2,b+=2);return b+(a>>31)},da;
function ea(a){for(var b in a)return b}function m(a){this.pd=a}m.prototype.toString=function(){return String.fromCharCode(this.pd)};function fa(a,b){return new a.Gc(b)}function n(a,b){return ha(a,b,0)}var ha=function ia(a,b,c){var f=new a.Gc(b[c]);if(c<b.length-1){a=a.cc;c+=1;for(var g=f.a,h=0;h<g.length;h++)g[h]=ia(a,b,c)}return f};
function ja(a){switch(typeof a){case "string":return q(ka);case "number":return la(a)?a<<24>>24===a?q(ma):a<<16>>16===a?q(na):q(oa):q(pa);case "boolean":return q(ra);case "undefined":return q(sa);default:return null===a?a.se():a instanceof r?q(ta):a instanceof m?q(ua):a&&a.$classData?q(a.$classData):null}}
function va(a){switch(typeof a){case "string":return"java.lang.String";case "number":return la(a)?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.se():a instanceof r?"java.lang.Long":a instanceof m?"java.lang.Character":a&&a.$classData?a.$classData.name:null.$a.name}}function wa(a){return void 0===a?"undefined":a.toString()}
function xa(a,b){return a&&a.$classData||null===a?a.J(b):"number"===typeof a?ba(a,b):a instanceof m?b instanceof m?t(a)===t(b):!1:u.prototype.J.call(a,b)}function ya(a){switch(typeof a){case "string":return za(a);case "number":return a=+a,Aa(Ba(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.Z():a instanceof m?t(a):Ca(a)}}function Da(a,b){if(0===b)throw new Ea("/ by zero");return a%b|0}
function Fa(a){return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}
var Ga=0,Ha="undefined"!==typeof WeakMap?new WeakMap:null,Ca=null!==Ha?function(a){switch(typeof a){case "string":case "number":case "bigint":case "boolean":case "undefined":return ya(a);default:if(null===a)return 0;var b=Ha.get(a);void 0===b&&(Ga=b=Ga+1|0,Ha.set(a,b));return b}}:function(a){switch(typeof a){case "string":case "number":case "bigint":case "boolean":case "undefined":return ya(a);default:if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(Object.isSealed(a))return 42;
Ga=b=Ga+1|0;return a.$idHashCode$0=b}null===a?0:42}};function la(a){return"number"===typeof a&&(a|0)===a&&1/a!==1/-0}var Ia=new m(0);function t(a){return null===a?0:a.pd}function Ja(a){return null===a?da:a}function v(){this.Gc=void 0;this.X=this.cc=this.ca=null;this.Y=0;this.gd=null;this.ac="";this.Jc=this.Ec=this.Fc=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}
function w(a,b,c,e){var f=new v;f.ca={};f.gd=a;f.ac=b;f.Jc=e;f.name=c;f.isPrimitive=!0;f.isInstance=function(){return!1};return f}function x(a,b,c,e,f){var g=new v,h=ea(a);g.ca=c;g.ac="L"+b+";";g.Jc=f||function(k,p){return!!(k&&k.$classData&&k.$classData.Y===p&&k.$classData.X.ca[h])};g.name=b;g.isInterface=!1;g.isInstance=e||function(k){return!!(k&&k.$classData&&k.$classData.ca[h])};return g}
function Ka(a){function b(k){if("number"===typeof k){this.a=Array(k);for(var p=0;p<k;p++)this.a[p]=e}else this.a=k}var c=new v,e="longZero"===a.gd?da:a.gd;b.prototype=new y;b.prototype.constructor=b;b.prototype.k=function(){return new b(this.a instanceof Array?this.a.slice(0):new this.a.constructor(this.a))};b.prototype.$classData=c;var f="["+a.ac,g=a.X||a,h=a.Y+1;c.Gc=b;c.ca={b:1,gc:1,c:1};c.cc=a;c.X=g;c.Y=h;c.ac=f;c.name=f;c.isArrayClass=!0;c.isInstance=function(k){return g.Jc(k,h)};return c}
function z(a){a.Ec||(a.Ec=Ka(a));return a.Ec}function q(a){a.Fc||(a.Fc=new La(a));return a.Fc}v.prototype.isAssignableFrom=function(a){return this.isPrimitive||a.isPrimitive?this===a:this.isInstance(a===ka?"":a===ra?!1:a===ma||a===na||a===oa||a===pa||a===Ma?0:a===ta?da:a===ua?Ia:a===sa?void 0:{$classData:a})};v.prototype.checkCast=function(){};v.prototype.getSuperclass=function(){return this.Ue?q(this.Ue):null};v.prototype.getComponentType=function(){return this.cc?q(this.cc):null};
v.prototype.newArrayOfThisClass=function(a){for(var b=this,c=0;c<a.length;c++)b=z(b);return n(b,a)};function Na(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==Oa)}function Pa(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==Qa)}function Ra(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==Sa)}function Ta(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==Ua)}
function Va(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==Wa)}function Xa(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==Ya)}function Za(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==$a)}function ab(a,b){return!(!a||!a.$classData||a.$classData.Y!==b||a.$classData.X!==bb)}
var Oa=w(!1,"Z","boolean",Na),Qa=w(0,"C","char",Pa),Sa=w(0,"B","byte",Ra),Ua=w(0,"S","short",Ta),Wa=w(0,"I","int",Va),Ya=w("longZero","J","long",Xa),$a=w(0,"F","float",Za),bb=w(0,"D","double",ab);function u(){}function y(){}y.prototype=u.prototype;u.prototype.Z=function(){return Ca(this)};u.prototype.J=function(a){return this===a};u.prototype.y=function(){var a=va(this),b=this.Z();return a+"@"+(+(b>>>0)).toString(16)};u.prototype.toString=function(){return this.y()};
function cb(a,b){if(a=a&&a.$classData){var c=a.Y||0;return!(c<b)&&(c>b||!a.X.isPrimitive)}return!1}var A=x({b:0},"java.lang.Object",{b:1},function(a){return null!==a},cb);u.prototype.$classData=A;function La(a){this.$a=a}La.prototype=new y;La.prototype.constructor=La;La.prototype.y=function(){return(this.$a.isInterface?"interface ":this.$a.isPrimitive?"":"class ")+this.$a.name};La.prototype.$classData=x({ye:0},"java.lang.Class",{ye:1,b:1});
function db(){this.ab=!1;this.vd=this.hc=this.zb=null;this.Kc=!1;this.xd=this.wd=0;eb=this;this.zb=(this.ab="undefined"!==typeof ArrayBuffer&&"undefined"!==typeof Int32Array&&"undefined"!==typeof Float32Array&&"undefined"!==typeof Float64Array)?new ArrayBuffer(8):null;this.hc=this.ab?new Int32Array(this.zb,0,2):null;this.ab&&new Float32Array(this.zb,0,2);this.vd=this.ab?new Float64Array(this.zb,0,1):null;if(this.ab)this.hc[0]=16909060,a=1===((new Int8Array(this.zb,0,8))[0]|0);else var a=!0;this.wd=
(this.Kc=a)?0:1;this.xd=this.Kc?1:0}db.prototype=new y;db.prototype.constructor=db;
function Aa(a,b){var c=b|0;if(c===b&&-Infinity!==1/b)return c;if(a.ab)a.vd[0]=b,a=new r(a.hc[a.xd]|0,a.hc[a.wd]|0);else{if(b!==b)a=!1,b=2047,c=+Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,c=0;else if(0===b)a=-Infinity===1/b,c=b=0;else{var e=(a=0>b)?-b:b;if(e>=+Math.pow(2,-1022)){c=+Math.pow(2,52);b=+Math.floor(+Math.log(e)/.6931471805599453)|0;1023<b&&(b=1023);var f=+Math.pow(2,b);f>e&&(b=-1+b|0,f/=2);f=e/f*c;e=+Math.floor(f);f-=e;e=.5>f?e:.5<f?1+e:0!==e%2?1+e:e;2<=e/c&&(b=1+b|
0,e=1);1023<b?(b=2047,e=0):(b=1023+b|0,e-=c);c=e}else b=e/+Math.pow(2,-1074),c=+Math.floor(b),e=b-c,b=0,c=.5>e?c:.5<e?1+c:0!==c%2?1+c:c}a=new r(c|0,(a?-2147483648:0)|b<<20|c/4294967296|0)}return a.I^a.N}db.prototype.$classData=x({Be:0},"java.lang.FloatingPointBits$",{Be:1,b:1});var eb=void 0;function Ba(){eb||(eb=new db);return eb}
function fb(){this.zd=this.Lc=null;gb=this;var a={"java.version":"1.8","java.vm.specification.version":"1.8","java.vm.specification.vendor":"Oracle Corporation","java.vm.specification.name":"Java Virtual Machine Specification","java.vm.name":"Scala.js"};a["java.vm.version"]=aa.linkerVersion;a["java.specification.version"]="1.8";a["java.specification.vendor"]="Oracle Corporation";a["java.specification.name"]="Java Platform API Specification";a["file.separator"]="/";a["path.separator"]=":";a["line.separator"]=
"\n";this.Lc=a;this.zd=null}fb.prototype=new y;fb.prototype.constructor=fb;function hb(a,b,c){null!==a.Lc?(ib||(ib=new jb),a=a.Lc,kb||(kb=new lb),b=kb.Ad.call(a,b)?a[b]:c):b=hb(a.zd,b,c);return b}fb.prototype.$classData=x({Ke:0},"java.lang.System$SystemProperties$",{Ke:1,b:1});var gb=void 0;function mb(){gb||(gb=new fb);return gb}function jb(){}jb.prototype=new y;jb.prototype.constructor=jb;jb.prototype.$classData=x({Me:0},"java.lang.Utils$",{Me:1,b:1});var ib=void 0;
function lb(){this.Ad=null;kb=this;this.Ad=Object.prototype.hasOwnProperty}lb.prototype=new y;lb.prototype.constructor=lb;lb.prototype.$classData=x({Ne:0},"java.lang.Utils$Cache$",{Ne:1,b:1});var kb=void 0;function nb(a){return!!(a&&a.$classData&&1===a.$classData.Y&&a.$classData.X.ca.Bd)}var sa=x({Bd:0},"java.lang.Void",{Bd:1,b:1},function(a){return void 0===a});function ob(){}ob.prototype=new y;ob.prototype.constructor=ob;ob.prototype.$classData=x({Oe:0},"java.lang.reflect.Array$",{Oe:1,b:1});
var pb=void 0;function qb(){}qb.prototype=new y;qb.prototype.constructor=qb;qb.prototype.$classData=x({Pe:0},"java.util.Arrays$",{Pe:1,b:1});var rb=void 0;function sb(){this.hd=this.id=null;this.Ka=0}sb.prototype=new y;sb.prototype.constructor=sb;function tb(a){0===(33554432&a.Ka)&&0===(33554432&a.Ka)&&(a.id=window,a.Ka|=33554432);return a.id}function ub(){var a=vb();0===(67108864&a.Ka)&&0===(67108864&a.Ka)&&(a.hd=tb(a).document,a.Ka|=67108864);return a.hd}
sb.prototype.$classData=x({je:0},"org.scalajs.dom.package$",{je:1,b:1});var wb=void 0;function vb(){wb||(wb=new sb);return wb}function xb(a,b,c){return a.g()?""+b+")":a.Zb(yb(),b,c,")").L.e}function zb(a,b,c,e,f){var g=b.L;0!==(c.length|0)&&(g.e=""+g.e+c);a=a.j();if(a.o())for(c=a.p(),g.e=""+g.e+c;a.o();)g.e=""+g.e+e,c=a.p(),g.e=""+g.e+c;0!==(f.length|0)&&(g.e=""+g.e+f);return b}
function Ab(){this.Jd=0;Bb=this;try{var a=hb(mb(),"scala.collection.immutable.IndexedSeq.defaultApplyPreferredMaxLength","64");var b=Cb(Db(),a)}catch(c){throw c;}this.Jd=b}Ab.prototype=new y;Ab.prototype.constructor=Ab;Ab.prototype.$classData=x({vf:0},"scala.collection.immutable.IndexedSeqDefaults$",{vf:1,b:1});var Bb=void 0;
function Eb(a,b,c){a.ya(c);c=-1+c|0;switch(c){case -1:break;case 0:a.m(b.u());break;case 1:a.i(b.d());a.m(b.u());break;case 2:a.n(b.f());a.i(b.d());a.m(b.u());break;case 3:a.s(b.h());a.n(b.f());a.i(b.d());a.m(b.u());break;case 4:a.A(b.r());a.s(b.h());a.n(b.f());a.i(b.d());a.m(b.u());break;case 5:a.da(b.O());a.A(b.r());a.s(b.h());a.n(b.f());a.i(b.d());a.m(b.u());break;default:throw new B(c);}}
function Fb(a,b,c){if(32<=c)if(1024>c)a.m(a.d().a[31&(b>>>5|0)]);else if(32768>c)a.i(a.f().a[31&(b>>>10|0)]),a.m(a.d().a[31&(b>>>5|0)]);else if(1048576>c)a.n(a.h().a[31&(b>>>15|0)]),a.i(a.f().a[31&(b>>>10|0)]),a.m(a.d().a[31&(b>>>5|0)]);else if(33554432>c)a.s(a.r().a[31&(b>>>20|0)]),a.n(a.h().a[31&(b>>>15|0)]),a.i(a.f().a[31&(b>>>10|0)]),a.m(a.d().a[31&(b>>>5|0)]);else if(1073741824>c)a.A(a.O().a[31&(b>>>25|0)]),a.s(a.r().a[31&(b>>>20|0)]),a.n(a.h().a[31&(b>>>15|0)]),a.i(a.f().a[31&(b>>>10|0)]),a.m(a.d().a[31&
(b>>>5|0)]);else throw Gb();}function C(a,b){var c=a.a[b];a.a[b]=null;return c.k()}function Hb(){}Hb.prototype=new y;Hb.prototype.constructor=Hb;function D(a,b,c){if(b===c)c=!0;else if(Ib(b))a:if(Ib(c))c=Jb(b,c);else{if(c instanceof m){if("number"===typeof b){c=+b===t(c);break a}if(b instanceof r){a=Ja(b);b=a.N;c=t(c);c=a.I===c&&b===c>>31;break a}}c=null===b?null===c:xa(b,c)}else c=b instanceof m?Kb(b,c):null===b?null===c:xa(b,c);return c}
function Jb(a,b){if("number"===typeof a){a=+a;if("number"===typeof b)return a===+b;if(b instanceof r){var c=Ja(b);b=c.I;c=c.N;return a===Lb(Mb(),b,c)}return!1}if(a instanceof r){c=Ja(a);a=c.I;c=c.N;if(b instanceof r){b=Ja(b);var e=b.N;return a===b.I&&c===e}return"number"===typeof b?(b=+b,Lb(Mb(),a,c)===b):!1}return null===a?null===b:xa(a,b)}
function Kb(a,b){if(b instanceof m)return t(a)===t(b);if(Ib(b)){if("number"===typeof b)return+b===t(a);if(b instanceof r){b=Ja(b);var c=b.N;a=t(a);return b.I===a&&c===a>>31}return null===b?null===a:xa(b,a)}return null===a&&null===b}Hb.prototype.$classData=x({gg:0},"scala.runtime.BoxesRunTime$",{gg:1,b:1});var Nb=void 0;function E(){Nb||(Nb=new Hb);return Nb}function Ob(){}Ob.prototype=new y;Ob.prototype.constructor=Ob;
function Pb(a,b,c,e){if(cb(b,1))b.a[c]=e;else if(Va(b,1))b.a[c]=e|0;else if(ab(b,1))b.a[c]=+e;else if(Xa(b,1))b.a[c]=Ja(e);else if(Za(b,1))b.a[c]=+e;else if(Pa(b,1))b.a[c]=t(e);else if(Ra(b,1))b.a[c]=e|0;else if(Ta(b,1))b.a[c]=e|0;else if(Na(b,1))b.a[c]=!!e;else if(nb(b))b.a[c]=void 0;else{if(null===b)throw new Qb;throw new B(b);}}
function Rb(a,b){pb||(pb=new ob);if(cb(b,1)||Na(b,1)||Pa(b,1)||Ra(b,1)||Ta(b,1)||Va(b,1)||Xa(b,1)||Za(b,1)||ab(b,1))a=b.a.length;else throw Sb("argument type mismatch");return a}Ob.prototype.$classData=x({jg:0},"scala.runtime.ScalaRunTime$",{jg:1,b:1});var Tb=void 0;function Ub(){Tb||(Tb=new Ob);return Tb}function Vb(){}Vb.prototype=new y;Vb.prototype.constructor=Vb;
function F(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=Fa(a);if(b===a)a=b;else{b=Mb();if(-9223372036854775808>a){b.Yb=-2147483648;var c=0}else if(0x7fffffffffffffff<=a)b.Yb=2147483647,c=-1;else{c=a|0;var e=a/4294967296|0;b.Yb=0>a&&0!==c?-1+e|0:e}b=b.Yb;a=Lb(Mb(),c,b)===a?c^b:Aa(Ba(),a)}return a}return b instanceof r?(a=Ja(b),b=new r(a.I,a.N),a=b.I,b=b.N,b===a>>31?a:a^b):ya(b)}function Wb(a,b){throw G(""+b);}Vb.prototype.$classData=x({mg:0},"scala.runtime.Statics$",{mg:1,b:1});
var Xb=void 0;function H(){Xb||(Xb=new Vb);return Xb}function Yb(){}Yb.prototype=new y;Yb.prototype.constructor=Yb;function Zb(a){$b||($b=new Yb);return a instanceof ac?a.Vb:a}Yb.prototype.$classData=x({fg:0},"scala.scalajs.runtime.package$",{fg:1,b:1});var $b=void 0;function bc(){}bc.prototype=new y;bc.prototype.constructor=bc;function cc(){}cc.prototype=bc.prototype;function I(a,b){b=l(-862048943,b);b=l(461845907,b<<15|b>>>17|0);a^=b;return-430675100+l(5,a<<13|a>>>19|0)|0}
function J(a){a=l(-2048144789,a^(a>>>16|0));a=l(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function dc(a){ec();var b=a.Qa();if(0===b)return za(a.Ca());var c=I(-889275714,za(a.Ca()));for(var e=0;e<b;){var f=a.Ra(e);c=I(c,F(H(),f));e=1+e|0}return J(c^b)}function fc(){}fc.prototype=new y;fc.prototype.constructor=fc;fc.prototype.$classData=x({ke:0},"scalajs.fun.Main$",{ke:1,b:1});var gc=void 0;function hc(a,b){return 0===b||b===(-1+a.W|0)}
function ic(a){if(null===a)throw new B(a);var b=a.la();a=a.ma();return fa(z(jc),[new K(-1+b|0,a),new K(1+b|0,a),new K(b,-1+a|0),new K(b,1+a|0)])}function kc(a,b){b=ic(b);for(var c=0;c<b.a.length;){var e=b.a[c];if(!a.ib.a[e.la()].a[e.ma()])return!1;c=1+c|0}return!0}function lc(a,b){if(null===b)throw new B(b);return!a.ib.a[b.la()].a[b.ma()]}function mc(a,b,c){return new nc(b*a.sa,c*a.sa)}
function oc(a,b,c,e,f){var g=mc(a,b.la(),b.ma());if(null===g)throw new B(g);b=g.jb();g=g.kb();a.B.beginPath();a.B.arc(b+a.sa/2,g+a.sa/2,c,0,6.283185307179586);a.B.fillStyle=f;a.B.fill();a.B.strokeStyle=e;a.B.stroke()}function pc(a,b,c,e,f){a.B.beginPath();a.B.moveTo(b,c);a.B.lineTo(e,f);a.B.stroke()}function qc(a,b,c,e,f){c=mc(a,b,c);if(null===c)throw new B(c);b=c.jb();c=c.kb();e=mc(a,e,f);if(null===e)throw new B(e);pc(a,b,c,e.jb(),e.kb())}
function rc(a,b){var c=L(a.La.ka,b),e=a.sa/6,f=a.sa/3;a.B.lineWidth=2;0===b?oc(a,c,f,"black","gray"):b===(-1+a.La.U|0)?(hc(a,c.la())||hc(a,c.ma())||!kc(a,c)?(b="darkgreen",e="limegreen"):(b="#aa0000",e="red"),oc(a,c,f,b,e)):oc(a,c,e,"blue","cornflowerblue")}
function sc(a){var b=ub().createElement("button");b.innerText="Go!";b.title="Click for a new random walk";b.onclick=function(f){return function(){tc(f.yc)}}(a);a=ub().createElement("output");var c=ub().createElement("div");c.style.padding="10px";c.appendChild(b);c.appendChild(a);b=ub().createElement("h3");b.innerText="Self avoiding random walks";var e=ub().getElementById("controls");e.appendChild(b);e.appendChild(c);return a}
function uc(a){this.Ac=this.B=this.Wb=this.ib=this.La=null;this.sa=this.xc=this.zc=0;this.kd=this.yc=null;this.Xb=a;this.W=1+(a<<1)|0;a=M();this.La=vc(new N,a);var b=this.W;a=this.W;wc||(wc=new xc);var c=n(z(z(Oa)),[b]),e=-1+b|0;if(!(0>=b))for(b=0;;){c.a[b]=n(z(Oa),[a]);if(b===e)break;b=1+b|0}this.ib=c;this.Wb=ub().getElementById("canvas");this.B=this.Wb.getContext("2d");a=Fa(.8*+tb(vb()).innerWidth);c=Fa(.8*+tb(vb()).innerHeight);this.Ac=new K(a,c);this.zc=this.Ac.la();this.xc=this.Ac.ma();this.Wb.width=
this.zc;this.Wb.height=this.xc;a=this.zc;c=this.xc;c=a<c?a:c;a=c/this.W;c/=this.W*a;this.B.setTransform(c,0,0,c,0,0);this.sa=a;this.yc=new yc(this);this.kd=sc(this)}uc.prototype=new y;uc.prototype.constructor=uc;uc.prototype.$classData=x({le:0},"scalajs.fun.randomWalks.RandomWalk",{le:1,b:1});
function zc(a){Ac(a);var b=1E3/a.jd;b=tb(vb()).setInterval(function(c){return function(){if(c.hb>=c.gb.La.U)var e=(Bc(c),void 0);else{e=c.gb;var f=c.hb;if(0<f){e.B.lineWidth=2;e.B.strokeStyle="blue";var g=L(e.La.ka,-1+f|0),h=L(e.La.ka,f),k=mc(e,g.la(),g.ma());if(null===k)throw new B(k);g=k.jb();k=k.kb();h=mc(e,h.la(),h.ma());if(null===h)throw new B(h);var p=e.sa/2;pc(e,g+p,k+p,h.jb()+p,h.kb()+p);rc(e,-1+f|0);rc(e,f)}c.hb=1+c.hb|0;e=void 0}return e}}(a),b)|0;a.wb=new Ec(b)}
function tc(a){var b=a.wb;if(Fc()===b)zc(a);else if(b instanceof Ec)Bc(a),zc(a);else throw new B(b);}function Bc(a){var b=a.wb;if(Fc()!==b)if(b instanceof Ec)b=b.Ab|0,tb(vb()).clearInterval(b),a.wb=Fc();else throw new B(b);}
function Gc(a){0===(16&a.fc)<<24>>24&&0===(16&a.fc)<<24>>24&&(a.ud=fa(z(Wa),[1632,1776,1984,2406,2534,2662,2790,2918,3046,3174,3302,3430,3664,3792,3872,4160,4240,6112,6160,6470,6608,6784,6800,6992,7088,7232,7248,42528,43216,43264,43472,43600,44016,65296,66720,69734,69872,69942,70096,71360,120782,120792,120802,120812,120822]),a.fc=(16|a.fc)<<24>>24);return a.ud}function Hc(){this.ud=null;this.fc=0}Hc.prototype=new y;Hc.prototype.constructor=Hc;
Hc.prototype.$classData=x({xe:0},"java.lang.Character$",{xe:1,b:1,c:1});var Ic=void 0;function Jc(a){throw new Kc('For input string: "'+a+'"');}function Lc(){}Lc.prototype=new y;Lc.prototype.constructor=Lc;
function Cb(a,b){a=null===b?0:b.length|0;0===a&&Jc(b);var c=65535&(b.charCodeAt(0)|0),e=45===c,f=e?2147483648:2147483647;c=e||43===c?1:0;c>=(b.length|0)&&Jc(b);for(var g=0;c!==a;){Ic||(Ic=new Hc);var h=Ic;var k=65535&(b.charCodeAt(c)|0);if(256>k)h=48<=k&&57>=k?-48+k|0:65<=k&&90>=k?-55+k|0:97<=k&&122>=k?-87+k|0:-1;else if(65313<=k&&65338>=k)h=-65303+k|0;else if(65345<=k&&65370>=k)h=-65335+k|0;else{var p=Gc(h);a:{rb||(rb=new qb);for(var Cc=k,qa=0,wd=p.a.length;;){if(qa===wd){p=-1-qa|0;break a}var Dc=
(qa+wd|0)>>>1|0,Me=p.a[Dc];if(Cc<Me)wd=Dc;else{if(D(E(),Cc,Me)){p=Dc;break a}qa=1+Dc|0}}}p=0>p?-2-p|0:p;0>p?h=-1:(h=k-Gc(h).a[p]|0,h=9<h?-1:h)}h=10>h?h:-1;g=10*g+h;(-1===h||g>f)&&Jc(b);c=1+c|0}return e?-g|0:g|0}Lc.prototype.$classData=x({Ee:0},"java.lang.Integer$",{Ee:1,b:1,c:1});var Mc=void 0;function Db(){Mc||(Mc=new Lc);return Mc}function Nc(){}Nc.prototype=new y;Nc.prototype.constructor=Nc;function Oc(){}Oc.prototype=Nc.prototype;function Ib(a){return a instanceof Nc||"number"===typeof a}
function O(a,b){a.$=b;a.fa=null;a.ga=!0;a.ha=!0;a.rd()}function Pc(){this.fa=this.$=null;this.ha=this.ga=!1}function Qc(){}Qc.prototype=Error.prototype;Pc.prototype=new Qc;Pc.prototype.constructor=Pc;function Rc(){}d=Rc.prototype=Pc.prototype;d.ec=function(){return this.$};d.rd=function(){"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)};d.y=function(){var a=va(this),b=this.ec();return null===b?a:a+": "+b};d.Z=function(){return u.prototype.Z.call(this)};
d.J=function(a){return u.prototype.J.call(this,a)};Object.defineProperty(Pc.prototype,"message",{get:function(){var a=this.ec();return null===a?"":a},configurable:!0});Object.defineProperty(Pc.prototype,"name",{get:function(){return va(this)},configurable:!0});Pc.prototype.toString=function(){return this.y()};function Sc(a,b){var c=-554899859^b.I;a.Mc=c>>>24|0|(65535&(5^b.N))<<8;a.Nc=16777215&c;a.Te=!1;return a}function Tc(){this.Nc=this.Mc=0;this.Te=!1}Tc.prototype=new y;
Tc.prototype.constructor=Tc;function Uc(a){var b=a.Nc,c=11+15525485*b;b=16777215&((c/16777216|0)+(16777215&(1502*b+15525485*a.Mc|0))|0);c=16777215&(c|0);a.Mc=b;a.Nc=c;return(b<<8|c>>16)>>>1|0}function Vc(a,b){if(0>=b)throw Sb("n must be positive");if((b&(-b|0))===b)a=Uc(a)>>ca(b);else a:for(;;){var c=Uc(a),e=Da(c,b);if(!(0>((c-e|0)+(-1+b|0)|0))){a=e;break a}}return a}Tc.prototype.$classData=x({Re:0},"java.util.Random",{Re:1,b:1,c:1});
function Wc(){var a=4294967296*+Math.random();return Fa(-2147483648+ +Math.floor(a))}function Xc(){}Xc.prototype=new y;Xc.prototype.constructor=Xc;Xc.prototype.$classData=x({Se:0},"java.util.Random$",{Se:1,b:1,c:1});var Yc=void 0;
function Zc(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var c=(32+ca(1E9)|0)-(0!==b?ca(b):32+ca(a)|0)|0,e=c,f=0===(32&e)?1E9<<e:0;e=0===(32&e)?5E8>>>(31-e|0)|0|0<<e:1E9<<e;var g=a,h=b;for(a=b=0;0<=c&&0!==(-2097152&h);){var k=g,p=h,Cc=f,qa=e;if(p===qa?(-2147483648^k)>=(-2147483648^Cc):(-2147483648^p)>=(-2147483648^qa))k=h,p=e,h=g-f|0,k=(-2147483648^h)>(-2147483648^g)?-1+(k-p|0)|0:k-p|0,g=h,h=k,32>c?b|=1<<c:a|=1<<c;c=-1+c|0;k=e>>>1|0;f=f>>>1|0|e<<31;e=k}c=h;if(0===c?-1147483648<=(-2147483648^
g):-2147483648<=(-2147483648^c))c=4294967296*h+ +(g>>>0),g=c/1E9,f=g/4294967296|0,e=b,b=g=e+(g|0)|0,a=(-2147483648^g)<(-2147483648^e)?1+(a+f|0)|0:a+f|0,g=c%1E9|0;c=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(c.length|0)+c}return b}function $c(){this.Yb=0}$c.prototype=new y;$c.prototype.constructor=$c;function Lb(a,b,c){return 0>c?-(4294967296*+((0!==b?~c:-c|0)>>>0)+ +((-b|0)>>>0)):4294967296*c+ +(b>>>0)}
$c.prototype.$classData=x({oe:0},"org.scalajs.linker.runtime.RuntimeLong$",{oe:1,b:1,c:1});var ad=void 0;function Mb(){ad||(ad=new $c);return ad}function bd(){}bd.prototype=new y;bd.prototype.constructor=bd;
function cd(a,b,c,e,f,g){a=ja(b);var h;if(h=!!a.$a.isArrayClass)h=!!ja(e).$a.isAssignableFrom(a.$a);if(h)if(b=b.a,e=e.a,b!==e||f<c||(c+g|0)<f)for(a=0;a<g;a=a+1|0)e[f+a|0]=b[c+a|0];else for(a=g-1|0;0<=a;a=a-1|0)e[f+a|0]=b[c+a|0];else for(a=c,c=c+g|0;a<c;){Ub();g=e;h=f;Ub();var k=b;if(cb(k,1)||Va(k,1)||ab(k,1)||Xa(k,1)||Za(k,1))k=k.a[a];else if(Pa(k,1))k=new m(k.a[a]);else if(Ra(k,1)||Ta(k,1)||Na(k,1)||nb(k))k=k.a[a];else{if(null===k)throw new Qb;throw new B(k);}Pb(0,g,h,k);a=1+a|0;f=1+f|0}}
bd.prototype.$classData=x({Ve:0},"scala.Array$",{Ve:1,b:1,c:1});var dd=void 0;function ed(){dd||(dd=new bd);return dd}function fd(a,b){for(b=b.j();b.o();)a.Za(b.p());return a}function gd(){}gd.prototype=new y;gd.prototype.constructor=gd;function hd(){}hd.prototype=gd.prototype;gd.prototype.y=function(){return"\x3cfunction0\x3e"};function id(){}id.prototype=new y;id.prototype.constructor=id;function jd(){}jd.prototype=id.prototype;id.prototype.y=function(){return"\x3cfunction1\x3e"};
function kd(a){this.ed=a}kd.prototype=new y;kd.prototype.constructor=kd;kd.prototype.y=function(){return""+this.ed};kd.prototype.$classData=x({hg:0},"scala.runtime.IntRef",{hg:1,b:1,c:1});function ld(a){this.fd=a}ld.prototype=new y;ld.prototype.constructor=ld;ld.prototype.y=function(){return""+this.fd};ld.prototype.$classData=x({ig:0},"scala.runtime.ObjectRef",{ig:1,b:1,c:1});function md(){this.Bb=null}md.prototype=new y;md.prototype.constructor=md;function nd(){}nd.prototype=md.prototype;
md.prototype.$classData=x({Ed:0},"scala.util.Random",{Ed:1,b:1,c:1});function od(){this.lc=0;pd=this;this.lc=za("Seq");za("Map");za("Set")}od.prototype=new cc;od.prototype.constructor=od;
function qd(a){var b=ec();if(a&&a.$classData&&a.$classData.ca.pb)a:{var c=b.lc;b=a.l();switch(b){case 0:a=J(c^0);break a;case 1:b=c;a=a.t(0);a=I(b,F(H(),a));a=J(a^1);break a;default:var e=a.t(0),f=F(H(),e);e=c=I(c,f);var g=a.t(1);g=F(H(),g);var h=g-f|0;for(f=2;f<b;){c=I(c,g);var k=a.t(f);k=F(H(),k);if(h!==(k-g|0)){c=I(c,k);for(f=1+f|0;f<b;)e=a.t(f),c=I(c,F(H(),e)),f=1+f|0;a=J(c^b);break a}g=k;f=1+f|0}a=J(I(I(e,h),g))}}else if(a instanceof rd){b=b.lc;f=0;g=b;c=e=k=h=0;for(var p=a;!p.g();){a=p.z();
p=p.M();a=F(H(),a);g=I(g,a);switch(h){case 0:c=a;h=1;break;case 1:k=a-e|0;h=2;break;case 2:k!==(a-e|0)&&(h=3)}e=a;f=1+f|0}2===h?(a=k,a=J(I(I(I(b,c),a),e))):a=J(g^f)}else a:if(b=b.lc,a=a.j(),a.o())if(c=a.p(),a.o()){e=a.p();g=F(H(),c);c=b=I(b,g);f=F(H(),e);g=f-g|0;for(e=2;a.o();){b=I(b,f);h=a.p();h=F(H(),h);if(g!==(h-f|0)){b=I(b,h);for(e=1+e|0;a.o();)c=a.p(),b=I(b,F(H(),c)),e=1+e|0;a=J(b^e);break a}f=h;e=1+e|0}a=J(I(I(c,g),f))}else a=I(b,F(H(),c)),a=J(a^1);else a=J(b^0);return a}
od.prototype.$classData=x({bf:0},"scala.util.hashing.MurmurHash3$",{bf:1,yg:1,b:1});var pd=void 0;function ec(){pd||(pd=new od);return pd}function yc(a){this.hb=this.jd=0;this.gb=this.wb=null;if(null===a)throw Zb(null);this.gb=a;this.wb=Fc();this.jd=60;this.hb=0}yc.prototype=new y;yc.prototype.constructor=yc;
function Ac(a){sd||(sd=new td);var b=Vc(sd.Bb,2147483647);a.gb.kd.innerText=" Using "+b+" as random seed";var c=a.gb,e=new md;b=Sc(new Tc,new r(b,b>>31));e.Bb=b;var f=c.W;b=-1+f|0;if(!(0>=f))for(f=0;;){var g=f,h=c.W,k=-1+h|0;if(!(0>=h))for(h=0;;){c.ib.a[g].a[h]=!1;if(h===k)break;h=1+h|0}if(f===b)break;f=1+f|0}f=new K(c.Xb,c.Xb);c.ib.a[c.Xb].a[c.Xb]=!0;b=new ud([f]);for(c.La=vc(new N,b);!hc(c,f.la())&&!hc(c,f.ma())&&!kc(c,f);){b=c;g=e;f=ic(f);for(g=Vc(g.Bb,f.a.length);!lc(b,f.a[g]);)g=Da(1+g|0,f.a.length);
f=f.a[g];c.ib.a[f.la()].a[f.ma()]=!0;vd(c.La,f)}c=a.gb;c.B.clearRect(0,0,c.W*c.sa,c.W*c.sa);c.B.lineWidth=.5;c.B.strokeStyle="gray";e=c.W;if(!(0>e))for(b=0;;){f=b;qc(c,f,0,f,c.W);if(b===e)break;b=1+b|0}e=c.W;if(!(0>e))for(b=0;;){f=b;qc(c,0,f,c.W,f);if(b===e)break;b=1+b|0}a.hb=0}yc.prototype.$classData=x({me:0},"scalajs.fun.randomWalks.RandomWalk$$anon$1",{me:1,b:1,og:1});
var ra=x({ue:0},"java.lang.Boolean",{ue:1,b:1,c:1,Aa:1},function(a){return"boolean"===typeof a}),ua=x({we:0},"java.lang.Character",{we:1,b:1,c:1,Aa:1},function(a){return a instanceof m});function xd(){this.fa=this.$=null;this.ha=this.ga=!1}xd.prototype=new Rc;xd.prototype.constructor=xd;function yd(){}yd.prototype=xd.prototype;xd.prototype.$classData=x({va:0},"java.lang.Exception",{va:1,Ba:1,b:1,c:1});
function zd(a,b){if(0>b)return 1;var c=a.q();if(0<=c)return c===b?0:c<b?-1:1;c=0;for(a=a.j();a.o();){if(c===b)return a.o()?1:0;a.p();c=1+c|0}return c-b|0}function Ad(a){if(a.g())throw a=new Bd,O(a,null),a;return a.P(1)}function Cd(){this.Ua=null;Dd=this;this.Ua=new Ed}Cd.prototype=new y;Cd.prototype.constructor=Cd;Cd.prototype.ea=function(a){return a.j()};Cd.prototype.$classData=x({hf:0},"scala.collection.Iterator$",{hf:1,b:1,wa:1,c:1});var Dd=void 0;function Fd(){Dd||(Dd=new Cd);return Dd}
function Gd(){}Gd.prototype=new y;Gd.prototype.constructor=Gd;function Hd(a,b){if(b&&b.$classData&&b.$classData.ca.Wa)return b;if(b&&b.$classData&&b.$classData.ca.C)return new Id(new P(function(c,e){return function(){return e.j()}}(a,b)));a=Jd(Kd(),b);return Ld(new Md,a)}Gd.prototype.ea=function(a){return Hd(this,a)};Gd.prototype.$classData=x({qf:0},"scala.collection.View$",{qf:1,b:1,wa:1,c:1});var Nd=void 0;function Od(a,b){this.Bf=a;this.Cf=b}Od.prototype=new y;Od.prototype.constructor=Od;
Od.prototype.z=function(){return this.Bf};Od.prototype.E=function(){return this.Cf};Od.prototype.$classData=x({Af:0},"scala.collection.immutable.LazyList$State$Cons",{Af:1,b:1,zf:1,c:1});function Pd(){}Pd.prototype=new y;Pd.prototype.constructor=Pd;Pd.prototype.Ic=function(){throw new Q("head of empty lazy list");};Pd.prototype.E=function(){throw Qd("tail of empty lazy list");};Pd.prototype.z=function(){this.Ic()};
Pd.prototype.$classData=x({Df:0},"scala.collection.immutable.LazyList$State$Empty$",{Df:1,b:1,zf:1,c:1});var Rd=void 0;function Sd(){Rd||(Rd=new Pd);return Rd}function P(a){this.ag=a}P.prototype=new hd;P.prototype.constructor=P;function Td(a){return(0,a.ag)()}P.prototype.$classData=x({$f:0},"scala.scalajs.runtime.AnonFunction0",{$f:1,Bg:1,b:1,ng:1});function Ud(a){this.cg=a}Ud.prototype=new jd;Ud.prototype.constructor=Ud;Ud.prototype.ta=function(a){return(0,this.cg)(a)};
Ud.prototype.$classData=x({bg:0},"scala.scalajs.runtime.AnonFunction1",{bg:1,Cg:1,b:1,ra:1});function td(){this.Bb=null;var a=new Tc;Yc||(Yc=new Xc);var b=Wc(),c=Wc();Sc(a,new r(c,b));this.Bb=a}td.prototype=new nd;td.prototype.constructor=td;td.prototype.$classData=x({af:0},"scala.util.Random$",{af:1,Ed:1,b:1,c:1});
var sd=void 0,ma=x({ve:0},"java.lang.Byte",{ve:1,mb:1,b:1,c:1,Aa:1},function(a){return"number"===typeof a&&a<<24>>24===a&&1/a!==1/-0}),Ma=x({ze:0},"java.lang.Double",{ze:1,mb:1,b:1,c:1,Aa:1},function(a){return"number"===typeof a}),pa=x({Ae:0},"java.lang.Float",{Ae:1,mb:1,b:1,c:1,Aa:1},function(a){return"number"===typeof a}),oa=x({De:0},"java.lang.Integer",{De:1,mb:1,b:1,c:1,Aa:1},function(a){return la(a)}),ta=x({Fe:0},"java.lang.Long",{Fe:1,mb:1,b:1,c:1,Aa:1},function(a){return a instanceof r});
function Vd(){this.fa=this.$=null;this.ha=this.ga=!1}Vd.prototype=new yd;Vd.prototype.constructor=Vd;function R(){}R.prototype=Vd.prototype;var na=x({Ie:0},"java.lang.Short",{Ie:1,mb:1,b:1,c:1,Aa:1},function(a){return"number"===typeof a&&a<<16>>16===a&&1/a!==1/-0});function za(a){for(var b=0,c=1,e=-1+(a.length|0)|0;0<=e;)b=b+l(65535&(a.charCodeAt(e)|0),c)|0,c=l(31,c),e=-1+e|0;return b}var ka=x({pe:0},"java.lang.String",{pe:1,b:1,c:1,Aa:1,td:1},function(a){return"string"===typeof a});
function Wd(a){a.e="";return a}function Xd(){this.e=null}Xd.prototype=new y;Xd.prototype.constructor=Xd;Xd.prototype.y=function(){return this.e};Xd.prototype.l=function(){return this.e.length|0};Xd.prototype.$classData=x({Je:0},"java.lang.StringBuilder",{Je:1,b:1,td:1,pg:1,c:1});function r(a,b){this.I=a;this.N=b}r.prototype=new Oc;r.prototype.constructor=r;r.prototype.J=function(a){return a instanceof r?this.I===a.I&&this.N===a.N:!1};r.prototype.Z=function(){return this.I^this.N};
r.prototype.y=function(){Mb();var a=this.I,b=this.N;return b===a>>31?""+a:0>b?"-"+Zc(-a|0,0!==a?~b:-b|0):Zc(a,b)};r.prototype.$classData=x({ne:0},"org.scalajs.linker.runtime.RuntimeLong",{ne:1,mb:1,b:1,c:1,Aa:1});function Yd(){}Yd.prototype=new y;Yd.prototype.constructor=Yd;function Zd(){}d=Zd.prototype=Yd.prototype;d.j=function(){return this};d.g=function(){return!this.o()};d.xb=function(a){for(var b=0;b<a&&this.o();)this.p(),b=1+b|0;return this};d.y=function(){return"\x3citerator\x3e"};
d.qd=function(a,b,c){var e=this.j(),f=b,g=Rb(Ub(),a)-b|0;for(c=b+(c<g?c:g)|0;f<c&&e.o();)Pb(Ub(),a,f,e.p()),f=1+f|0;return f-b|0};d.Zb=function(a,b,c,e){return zb(this,a,b,c,e)};d.q=function(){return-1};function $d(){this.Db=null}$d.prototype=new y;$d.prototype.constructor=$d;function ae(){}ae.prototype=$d.prototype;$d.prototype.dc=function(a){return this.Db.ea(a)};$d.prototype.ea=function(a){return this.dc(a)};function be(a){return 0===a.T(0)}
function ce(a,b){var c=a.q();if(-1!==c){var e=b.q();c=-1!==e&&c!==e}else c=!1;if(c)return!1;a:{a=a.j();for(b=b.j();a.o()&&b.o();)if(!D(E(),a.p(),b.p())){b=!1;break a}b=a.o()===b.o()}return b}function de(){this.Wc=null;ee=this;this.Wc=fe(new S(new P(function(){return function(){return Sd()}}(this))))}de.prototype=new y;de.prototype.constructor=de;
function ge(a,b,c){return new S(new P(function(e,f,g){return function(){for(var h=f.fd,k=g.ed;0<k&&!h.g();)h=T(h).E(),f.fd=h,k=-1+k|0,g.ed=k;return T(h)}}(a,new ld(b),new kd(c))))}function Jd(a,b){return b instanceof S?b:0===b.q()?a.Wc:new S(new P(function(c,e){return function(){return he(Kd(),e.j())}}(a,b)))}function he(a,b){if(b.o()){var c=b.p();return new Od(c,new S(new P(function(e,f){return function(){return he(Kd(),f)}}(a,b))))}return Sd()}de.prototype.ea=function(a){return Jd(this,a)};
de.prototype.$classData=x({xf:0},"scala.collection.immutable.LazyList$",{xf:1,b:1,Va:1,wa:1,c:1});var ee=void 0;function Kd(){ee||(ee=new de);return ee}function ie(){je=this}ie.prototype=new y;ie.prototype.constructor=ie;function ke(a,b){a=a.ic();b.q();a.Oa(b);return a.Da()}ie.prototype.ic=function(){var a=yb();return new U(a,new Ud(function(){return function(b){return new le(b)}}(this)))};ie.prototype.$classData=x({Mf:0},"scala.collection.immutable.WrappedString$",{Mf:1,b:1,Ag:1,zg:1,c:1});
var je=void 0;function me(){je||(je=new ie);return je}function U(a,b){this.ce=this.vc=null;if(null===a)throw Zb(null);this.vc=a;this.ce=b}U.prototype=new y;U.prototype.constructor=U;U.prototype.Da=function(){return this.ce.ta(this.vc.Da())};U.prototype.Oa=function(a){this.vc.Oa(a);return this};U.prototype.Za=function(a){this.vc.Za(a)};U.prototype.$classData=x({Rf:0},"scala.collection.mutable.Builder$$anon$1",{Rf:1,b:1,uc:1,Tb:1,Sb:1});
function Ea(a){this.fa=this.$=null;this.ha=this.ga=!1;O(this,a)}Ea.prototype=new R;Ea.prototype.constructor=Ea;Ea.prototype.$classData=x({te:0},"java.lang.ArithmeticException",{te:1,Pa:1,va:1,Ba:1,b:1,c:1});function Sb(a){var b=new ne;O(b,a);return b}function Gb(){var a=new ne;O(a,null);return a}function ne(){this.fa=this.$=null;this.ha=this.ga=!1}ne.prototype=new R;ne.prototype.constructor=ne;function oe(){}oe.prototype=ne.prototype;
ne.prototype.$classData=x({yd:0},"java.lang.IllegalArgumentException",{yd:1,Pa:1,va:1,Ba:1,b:1,c:1});function G(a){var b=new pe;O(b,a);return b}function pe(){this.fa=this.$=null;this.ha=this.ga=!1}pe.prototype=new R;pe.prototype.constructor=pe;pe.prototype.$classData=x({Ce:0},"java.lang.IndexOutOfBoundsException",{Ce:1,Pa:1,va:1,Ba:1,b:1,c:1});function Qb(){this.fa=this.$=null;this.ha=this.ga=!1;O(this,null)}Qb.prototype=new R;Qb.prototype.constructor=Qb;
Qb.prototype.$classData=x({Ge:0},"java.lang.NullPointerException",{Ge:1,Pa:1,va:1,Ba:1,b:1,c:1});function Qd(a){var b=new Bd;O(b,a);return b}function Bd(){this.fa=this.$=null;this.ha=this.ga=!1}Bd.prototype=new R;Bd.prototype.constructor=Bd;Bd.prototype.$classData=x({Le:0},"java.lang.UnsupportedOperationException",{Le:1,Pa:1,va:1,Ba:1,b:1,c:1});function Q(a){this.fa=this.$=null;this.ha=this.ga=!1;O(this,a)}Q.prototype=new R;Q.prototype.constructor=Q;
Q.prototype.$classData=x({Qe:0},"java.util.NoSuchElementException",{Qe:1,Pa:1,va:1,Ba:1,b:1,c:1});function B(a){this.fa=this.$=null;this.ha=this.ga=!1;this.Cd=null;this.Oc=!1;this.jc=a;O(this,null)}B.prototype=new R;B.prototype.constructor=B;
B.prototype.ec=function(){if(!this.Oc&&!this.Oc){if(null===this.jc)var a="null";else try{a=wa(this.jc)+" (of class "+va(this.jc)+")"}catch(b){if($b||($b=new Yb),null!==(b instanceof Pc?b:new ac(b)))a="an instance of class "+va(this.jc);else throw b;}this.Cd=a;this.Oc=!0}return this.Cd};B.prototype.$classData=x({We:0},"scala.MatchError",{We:1,Pa:1,va:1,Ba:1,b:1,c:1});function qe(){}qe.prototype=new y;qe.prototype.constructor=qe;function re(){}re.prototype=qe.prototype;
qe.prototype.g=function(){return this===Fc()};qe.prototype.q=function(){return this.g()?0:1};qe.prototype.j=function(){if(this.g())return Fd().Ua;Fd();var a=this.sd();return new se(a)};function te(){this.Dc=this.Cc=null}te.prototype=new y;te.prototype.constructor=te;function ue(){}d=ue.prototype=te.prototype;d.Qa=function(){return 2};d.Ra=function(a){a:switch(a){case 0:a=this.Ma();break a;case 1:a=this.Na();break a;default:throw G(a+" is out of bounds (min 0, max 1)");}return a};d.Ma=function(){return this.Cc};
d.Na=function(){return this.Dc};d.y=function(){return"("+this.Ma()+","+this.Na()+")"};d.Ca=function(){return"Tuple2"};d.Z=function(){return dc(this)};d.J=function(a){return this===a?!0:a instanceof te?D(E(),this.Ma(),a.Ma())&&D(E(),this.Na(),a.Na()):!1};d.jb=function(){return+this.Ma()};d.la=function(){return this.Ma()|0};d.kb=function(){return+this.Na()};d.ma=function(){return this.Na()|0};var jc=x({Bc:0},"scala.Tuple2",{Bc:1,b:1,Dd:1,Sa:1,F:1,c:1});te.prototype.$classData=jc;
function ve(a,b){return a.yb(new V(a,b))}function Ed(){}Ed.prototype=new Zd;Ed.prototype.constructor=Ed;Ed.prototype.o=function(){return!1};Ed.prototype.q=function(){return 0};Ed.prototype.p=function(){throw new Q("next on empty iterator");};Ed.prototype.$classData=x({jf:0},"scala.collection.Iterator$$anon$19",{jf:1,ob:1,b:1,qb:1,v:1,x:1});function se(a){this.lf=a;this.Sc=!1}se.prototype=new Zd;se.prototype.constructor=se;se.prototype.o=function(){return!this.Sc};
se.prototype.p=function(){if(this.Sc)return Fd().Ua.p();this.Sc=!0;return this.lf};se.prototype.$classData=x({kf:0},"scala.collection.Iterator$$anon$20",{kf:1,ob:1,b:1,qb:1,v:1,x:1});function L(a,b){if(0>b)throw G(""+b);a=a.P(b);if(a.g())throw G(""+b);return a.z()}function we(a,b){if(b&&b.$classData&&b.$classData.ca.Tc)a:for(;;){if(a===b){a=!0;break a}if((a.g()?0:!b.g())&&D(E(),a.z(),b.z()))a=a.M(),b=b.M();else{a=a.g()&&b.g();break a}}else a=ce(a,b);return a}function xe(a){this.nc=a}
xe.prototype=new Zd;xe.prototype.constructor=xe;xe.prototype.o=function(){return!this.nc.g()};xe.prototype.p=function(){var a=this.nc.z();this.nc=this.nc.M();return a};xe.prototype.$classData=x({of:0},"scala.collection.StrictOptimizedLinearSeqOps$$anon$1",{of:1,ob:1,b:1,qb:1,v:1,x:1});function ye(){this.Db=null;this.Db=ze()}ye.prototype=new ae;ye.prototype.constructor=ye;ye.prototype.ea=function(a){return Ae(a)?a:$d.prototype.dc.call(this,a)};
ye.prototype.dc=function(a){return Ae(a)?a:$d.prototype.dc.call(this,a)};ye.prototype.$classData=x({uf:0},"scala.collection.immutable.IndexedSeq$",{uf:1,mf:1,b:1,Va:1,wa:1,c:1});var Be=void 0;function Ce(a){this.Jb=a}Ce.prototype=new Zd;Ce.prototype.constructor=Ce;Ce.prototype.o=function(){return!this.Jb.g()};Ce.prototype.p=function(){if(this.Jb.g())return Fd().Ua.p();var a=T(this.Jb).z();this.Jb=T(this.Jb).E();return a};
Ce.prototype.$classData=x({yf:0},"scala.collection.immutable.LazyList$LazyIterator",{yf:1,ob:1,b:1,qb:1,v:1,x:1});function De(){Ee=this}De.prototype=new y;De.prototype.constructor=De;De.prototype.ea=function(a){return a instanceof rd?a:0===a.q()?M():a instanceof N?Fe(a):Fe(vc(new N,a))};De.prototype.$classData=x({Ff:0},"scala.collection.immutable.List$",{Ff:1,b:1,Fb:1,Va:1,wa:1,c:1});var Ee=void 0;
function Ge(){this.rc=null;this.Pd=0;He=this;this.rc=new W(0,0,0);try{var a=hb(mb(),"scala.collection.immutable.Vector.defaultApplyPreferredMaxLength","1024");var b=Cb(Db(),a)}catch(c){throw c;}this.Pd=b}Ge.prototype=new y;Ge.prototype.constructor=Ge;
function Ie(a,b){if(b instanceof W)return b;var c=b.q();if(0===c)return a.rc;if(0<c&&32>=c){a=n(z(A),[c]);var e=b.j();b=Rb(Ub(),a);e=e.j();for(var f=0;f<b&&e.o();)Pb(Ub(),a,f,e.p()),f=1+f|0;c=new W(0,c,0);c.Pb=1;c.ia=a;return c}return Je(Ke(new Le,b))}Ge.prototype.ea=function(a){return Ie(this,a)};Ge.prototype.$classData=x({If:0},"scala.collection.immutable.Vector$",{If:1,b:1,Fb:1,Va:1,wa:1,c:1});var He=void 0;function ze(){He||(He=new Ge);return He}function Ne(){}Ne.prototype=new y;
Ne.prototype.constructor=Ne;
function Oe(a,b,c,e){a=b.a.length;var f=a>>31,g=e>>31;if(!(g===f?(-2147483648^e)<=(-2147483648^a):g<f)){f=new r(a,f);a=f.I<<1;f=f.I>>>31|0|f.N<<1;f=(0===f?-2147483632<(-2147483648^a):0<f)?new r(a,f):new r(16,0);a=f.I;for(f=f.N;;){g=e>>31;var h=a,k=f;if(g===k?(-2147483648^e)>(-2147483648^h):g>k)f=a>>>31|0|f<<1,a<<=1;else break}e=f;if(0===e?-1<(-2147483648^a):0<e){if(2147483647===c)throw b=new xd,O(b,"Collections can not have more than 2147483647 elements"),Zb(b);a=2147483647}e=a;e=n(z(A),[e]);cd(ed(),
b,0,e,0,c);b=e}return b}Ne.prototype.ea=function(a){var b=a.q();if(0<=b){var c=n(z(A),[16<b?b:16]);a=a.j();var e=-1+b|0;if(!(0>=b))for(var f=0;;){c.a[f]=a.p();if(f===e)break;f=1+f|0}a=new Pe;a.qa=c;a.w=b;b=a}else b=new Pe,c=n(z(A),[16]),b.qa=c,b.w=0,a instanceof Pe?(c=b.w+a.w|0,b.qa=Oe(Qe(),b.qa,b.w,c),cd(ed(),a.qa,0,b.qa,b.w,a.w),b.w=b.w+a.w|0):fd(b,a);return b};Ne.prototype.$classData=x({Of:0},"scala.collection.mutable.ArrayBuffer$",{Of:1,b:1,Fb:1,Va:1,wa:1,c:1});var Re=void 0;
function Qe(){Re||(Re=new Ne);return Re}function Se(){this.Db=null;this.Db=Qe()}Se.prototype=new ae;Se.prototype.constructor=Se;Se.prototype.$classData=x({Tf:0},"scala.collection.mutable.IndexedSeq$",{Tf:1,mf:1,b:1,Va:1,wa:1,c:1});var Te=void 0;function Ue(){}Ue.prototype=new y;Ue.prototype.constructor=Ue;Ue.prototype.ea=function(a){return vc(new N,a)};Ue.prototype.$classData=x({Vf:0},"scala.collection.mutable.ListBuffer$",{Vf:1,b:1,Fb:1,Va:1,wa:1,c:1});var Ve=void 0;
function We(a){this.ie=0;this.lg=a;this.wc=0;this.ie=a.Qa()}We.prototype=new Zd;We.prototype.constructor=We;We.prototype.o=function(){return this.wc<this.ie};We.prototype.p=function(){var a=this.lg.Ra(this.wc);this.wc=1+this.wc|0;return a};We.prototype.$classData=x({kg:0},"scala.runtime.ScalaRunTime$$anon$1",{kg:1,ob:1,b:1,qb:1,v:1,x:1});function Xe(){}Xe.prototype=new y;Xe.prototype.constructor=Xe;Xe.prototype.ea=function(a){var b=new Ye;Ze(b);return fd(b,a).Da()};
Xe.prototype.$classData=x({Zf:0},"scala.scalajs.js.WrappedArray$",{Zf:1,b:1,Fb:1,Va:1,wa:1,c:1});var $e=void 0;function af(){}af.prototype=new y;af.prototype.constructor=af;af.prototype.ic=function(){return new U(Ze(new Ye),new Ud(function(){return function(a){return new ud(a.Ya)}}(this)))};af.prototype.ea=function(a){return this.ic().Oa(a).Da()};af.prototype.$classData=x({eg:0},"scala.scalajs.runtime.WrappedVarArgs$",{eg:1,b:1,Fb:1,Va:1,wa:1,c:1});var bf=void 0;
function Kc(a){this.fa=this.$=null;this.ha=this.ga=!1;O(this,a)}Kc.prototype=new oe;Kc.prototype.constructor=Kc;Kc.prototype.$classData=x({He:0},"java.lang.NumberFormatException",{He:1,yd:1,Pa:1,va:1,Ba:1,b:1,c:1});function cf(){}cf.prototype=new re;cf.prototype.constructor=cf;d=cf.prototype;d.Ca=function(){return"None"};d.Qa=function(){return 0};d.Ra=function(a){return Wb(H(),a)};d.Z=function(){return 2433880};d.y=function(){return"None"};d.sd=function(){throw new Q("None.get");};
d.$classData=x({Xe:0},"scala.None$",{Xe:1,Ye:1,b:1,v:1,Sa:1,F:1,c:1});var df=void 0;function Fc(){df||(df=new cf);return df}function Ec(a){this.Ab=a}Ec.prototype=new re;Ec.prototype.constructor=Ec;d=Ec.prototype;d.sd=function(){return this.Ab};d.Ca=function(){return"Some"};d.Qa=function(){return 1};d.Ra=function(a){return 0===a?this.Ab:Wb(H(),a)};d.Z=function(){return dc(this)};d.y=function(){Ub();return xb(new We(this),this.Ca()+"(",",")};
d.J=function(a){return this===a?!0:a instanceof Ec?D(E(),this.Ab,a.Ab):!1};d.$classData=x({Ze:0},"scala.Some",{Ze:1,Ye:1,b:1,v:1,Sa:1,F:1,c:1});function ef(){}ef.prototype=new y;ef.prototype.constructor=ef;function ff(){}d=ff.prototype=ef.prototype;d.ua=function(){return this.V()};d.Hc=function(a){return this.za().ea(a)};d.z=function(){return this.j().p()};d.P=function(a){return this.yb(gf(new X,this,a))};d.M=function(){return Ad(this)};d.g=function(){return!this.j().o()};
d.Zb=function(a,b,c,e){return zb(this,a,b,c,e)};d.q=function(){return-1};d.yb=function(a){return this.Hc(a)};function Y(a){this.cb=0;this.gf=a;this.Cb=0;this.cb=a.l()}Y.prototype=new Zd;Y.prototype.constructor=Y;d=Y.prototype;d.q=function(){return this.cb};d.o=function(){return 0<this.cb};d.p=function(){if(this.o()){var a=this.gf.t(this.Cb);this.Cb=1+this.Cb|0;this.cb=-1+this.cb|0;return a}return Fd().Ua.p()};d.xb=function(a){0<a&&(this.Cb=this.Cb+a|0,a=this.cb-a|0,this.cb=0>a?0:a);return this};
d.$classData=x({ff:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{ff:1,ob:1,b:1,qb:1,v:1,x:1,c:1});
function hf(a){if(a.oa>=a.eb.a.length){var b=32+a.Mb|0,c=a.Mb^b;if(1024>c)1===a.S()&&(a.i(n(z(z(A)),[32])),a.d().a[0]=a.u(),a.ya(1+a.S()|0)),a.m(n(z(A),[32])),a.d().a[31&(b>>>5|0)]=a.u();else if(32768>c)2===a.S()&&(a.n(n(z(z(z(A))),[32])),a.f().a[0]=a.d(),a.ya(1+a.S()|0)),a.m(n(z(A),[32])),a.i(n(z(z(A)),[32])),a.d().a[31&(b>>>5|0)]=a.u(),a.f().a[31&(b>>>10|0)]=a.d();else if(1048576>c)3===a.S()&&(a.s(n(z(z(z(z(A)))),[32])),a.h().a[0]=a.f(),a.ya(1+a.S()|0)),a.m(n(z(A),[32])),a.i(n(z(z(A)),[32])),a.n(n(z(z(z(A))),
[32])),a.d().a[31&(b>>>5|0)]=a.u(),a.f().a[31&(b>>>10|0)]=a.d(),a.h().a[31&(b>>>15|0)]=a.f();else if(33554432>c)4===a.S()&&(a.A(n(z(z(z(z(z(A))))),[32])),a.r().a[0]=a.h(),a.ya(1+a.S()|0)),a.m(n(z(A),[32])),a.i(n(z(z(A)),[32])),a.n(n(z(z(z(A))),[32])),a.s(n(z(z(z(z(A)))),[32])),a.d().a[31&(b>>>5|0)]=a.u(),a.f().a[31&(b>>>10|0)]=a.d(),a.h().a[31&(b>>>15|0)]=a.f(),a.r().a[31&(b>>>20|0)]=a.h();else if(1073741824>c)5===a.S()&&(a.da(n(z(z(z(z(z(z(A)))))),[32])),a.O().a[0]=a.r(),a.ya(1+a.S()|0)),a.m(n(z(A),
[32])),a.i(n(z(z(A)),[32])),a.n(n(z(z(z(A))),[32])),a.s(n(z(z(z(z(A)))),[32])),a.A(n(z(z(z(z(z(A))))),[32])),a.d().a[31&(b>>>5|0)]=a.u(),a.f().a[31&(b>>>10|0)]=a.d(),a.h().a[31&(b>>>15|0)]=a.f(),a.r().a[31&(b>>>20|0)]=a.h(),a.O().a[31&(b>>>25|0)]=a.r();else throw Gb();a.Mb=b;a.oa=0}}function Le(){this.Nb=this.oa=this.Mb=0;this.Ud=this.Td=this.Sd=this.Rd=this.Qd=this.eb=null;this.eb=n(z(A),[32]);this.Nb=1;this.oa=this.Mb=0}Le.prototype=new y;Le.prototype.constructor=Le;d=Le.prototype;d.S=function(){return this.Nb};
d.ya=function(a){this.Nb=a};d.u=function(){return this.eb};d.m=function(a){this.eb=a};d.d=function(){return this.Qd};d.i=function(a){this.Qd=a};d.f=function(){return this.Rd};d.n=function(a){this.Rd=a};d.h=function(){return this.Sd};d.s=function(a){this.Sd=a};d.r=function(){return this.Td};d.A=function(a){this.Td=a};d.O=function(){return this.Ud};d.da=function(a){this.Ud=a};function Ke(a,b){for(b=b.j();b.o();)hf(a),a.oa=a.oa+b.qd(a.eb,a.oa,a.eb.a.length-a.oa|0)|0;return a}
function Je(a){var b=a.Mb+a.oa|0;if(0===b)return ze().rc;var c=new W(0,b,0);Eb(c,a,a.Nb);1<a.Nb&&Fb(c,0,-1+b|0);return c}d.Da=function(){return Je(this)};d.Oa=function(a){return Ke(this,a)};d.Za=function(a){hf(this);this.eb.a[this.oa]=a;this.oa=1+this.oa|0};d.$classData=x({Jf:0},"scala.collection.immutable.VectorBuilder",{Jf:1,b:1,fe:1,uc:1,Tb:1,Sb:1,$d:1});
function jf(a){if(a.D===a.Ob)if((a.aa+a.D|0)<a.Xa){var b=32+a.aa|0,c=a.aa^b;if(1024>c)a.m(a.d().a[31&(b>>>5|0)]);else if(32768>c)a.i(a.f().a[31&(b>>>10|0)]),a.m(a.d().a[0]);else if(1048576>c)a.n(a.h().a[31&(b>>>15|0)]),a.i(a.f().a[0]),a.m(a.d().a[0]);else if(33554432>c)a.s(a.r().a[31&(b>>>20|0)]),a.n(a.h().a[0]),a.i(a.f().a[0]),a.m(a.d().a[0]);else if(1073741824>c)a.A(a.O().a[31&(b>>>25|0)]),a.s(a.r().a[0]),a.n(a.h().a[0]),a.i(a.f().a[0]),a.m(a.d().a[0]);else throw Gb();a.aa=b;b=a.Xa-a.aa|0;a.Ob=
32>b?b:32;a.D=0}else a.vb=!1}function kf(a,b){this.Ob=0;this.vb=!1;this.sc=0;this.Zd=this.Yd=this.Xd=this.Wd=this.Vd=this.tc=null;this.Xa=b;this.aa=-32&a;this.D=31&a;a=this.Xa-this.aa|0;this.Ob=32>a?a:32;this.vb=(this.aa+this.D|0)<this.Xa}kf.prototype=new Zd;kf.prototype.constructor=kf;d=kf.prototype;d.S=function(){return this.sc};d.ya=function(a){this.sc=a};d.u=function(){return this.tc};d.m=function(a){this.tc=a};d.d=function(){return this.Vd};d.i=function(a){this.Vd=a};d.f=function(){return this.Wd};
d.n=function(a){this.Wd=a};d.h=function(){return this.Xd};d.s=function(a){this.Xd=a};d.r=function(){return this.Yd};d.A=function(a){this.Yd=a};d.O=function(){return this.Zd};d.da=function(a){this.Zd=a};d.o=function(){return this.vb};
d.xb=function(a){if(0<a){var b=this.D,c=b>>31,e=a>>31;a=b+a|0;c=(-2147483648^a)<(-2147483648^b)?1+(c+e|0)|0:c+e|0;e=this.aa;var f=e>>31;b=e+a|0;c=(-2147483648^b)<(-2147483648^e)?1+(f+c|0)|0:f+c|0;e=this.Xa;f=e>>31;(c===f?(-2147483648^b)<(-2147483648^e):c<f)?(this.D=a,32<=this.D&&(a=this.aa=-32&(this.aa+this.D|0),b=this.sc,5<b&&this.A(this.O().a[31&(a>>>25|0)]),4<b&&this.s(this.r().a[31&(a>>>20|0)]),3<b&&this.n(this.h().a[31&(a>>>15|0)]),2<b&&this.i(this.f().a[31&(a>>>10|0)]),1<b&&this.m(this.d().a[31&
(a>>>5|0)]),a=this.Xa-this.aa|0,this.Ob=32>a?a:32,this.D&=31)):(this.vb=!1,this.Xa=0)}return this};d.p=function(){if(!this.vb)throw new Q("reached iterator end");var a=this.tc.a[this.D];this.D=1+this.D|0;jf(this);return a};d.qd=function(a,b,c){var e=Rb(Ub(),a),f=lf(this);f=c<f?c:f;var g=e-b|0;f=f<g?f:g;f=0<f?f:0;for(g=0;this.vb&&g<f;){var h=b+g|0,k=this.Ob-this.D|0,p=c-g|0;k=p<k?p:k;p=e-h|0;k=k<p?k:p;k=0<k?k:0;cd(ed(),this.tc,this.D,a,h,k);g=g+k|0;this.D=this.D+k|0;jf(this)}return g};
function lf(a){a=a.Xa-(a.aa+a.D|0)|0;return 0<a?a:0}d.q=function(){return lf(this)};d.$classData=x({Kf:0},"scala.collection.immutable.VectorIterator",{Kf:1,ob:1,b:1,qb:1,v:1,x:1,$d:1});function nc(a,b){this.ld=a;this.md=b;this.Dc=this.Cc=null}nc.prototype=new ue;nc.prototype.constructor=nc;d=nc.prototype;d.jb=function(){return this.ld};d.kb=function(){return this.md};d.Na=function(){return this.md};d.Ma=function(){return this.ld};
d.$classData=x({qe:0},"scala.Tuple2$mcDD$sp",{qe:1,Bc:1,b:1,Dd:1,Sa:1,F:1,c:1,qg:1});function K(a,b){this.nd=a;this.od=b;this.Dc=this.Cc=null}K.prototype=new ue;K.prototype.constructor=K;d=K.prototype;d.la=function(){return this.nd};d.ma=function(){return this.od};d.Na=function(){return this.od};d.Ma=function(){return this.nd};d.$classData=x({re:0},"scala.Tuple2$mcII$sp",{re:1,Bc:1,b:1,Dd:1,Sa:1,F:1,c:1,rg:1});function mf(){this.Pc=null;this.kc=0}mf.prototype=new y;mf.prototype.constructor=mf;
function nf(){}nf.prototype=mf.prototype;mf.prototype.y=function(){return this.Pc};mf.prototype.J=function(a){return this===a};mf.prototype.Z=function(){return this.kc};function ac(a){this.fa=this.$=null;this.ha=this.ga=!1;this.Vb=a;O(this,null)}ac.prototype=new R;ac.prototype.constructor=ac;d=ac.prototype;d.ec=function(){return wa(this.Vb)};d.rd=function(){};d.Ca=function(){return"JavaScriptException"};d.Qa=function(){return 1};d.Ra=function(a){return 0===a?this.Vb:Wb(H(),a)};d.Z=function(){return dc(this)};
d.J=function(a){if(this===a)return!0;if(a instanceof ac){var b=this.Vb;a=a.Vb;return D(E(),b,a)}return!1};d.$classData=x({Xf:0},"scala.scalajs.js.JavaScriptException",{Xf:1,Pa:1,va:1,Ba:1,b:1,c:1,Sa:1,F:1});function of(){this.Pc=null;this.kc=0}of.prototype=new nf;of.prototype.constructor=of;function pf(){}pf.prototype=of.prototype;function qf(){}qf.prototype=new ff;qf.prototype.constructor=qf;function rf(){}rf.prototype=qf.prototype;qf.prototype.za=function(){Nd||(Nd=new Gd);return Nd};
qf.prototype.y=function(){return this.ua()+"(\x3cnot computed\x3e)"};qf.prototype.V=function(){return"View"};function xc(){this.kc=0;this.Pc="Boolean";this.kc=Ca(this)}xc.prototype=new pf;xc.prototype.constructor=xc;xc.prototype.$classData=x({$e:0},"scala.reflect.ManifestFactory$BooleanManifest$",{$e:1,wg:1,sg:1,b:1,vg:1,ug:1,tg:1,xg:1,c:1,F:1});var wc=void 0;function sf(a,b){return a===b?!0:b&&b.$classData&&b.$classData.ca.xa?b===a||b.bc(a)&&a.nb(b):!1}function Id(a){this.sf=a}Id.prototype=new rf;
Id.prototype.constructor=Id;Id.prototype.j=function(){return Td(this.sf)};Id.prototype.$classData=x({rf:0},"scala.collection.View$$anon$1",{rf:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1});function gf(a,b,c){a.Gb=b;a.oc=c;a.ub=0<c?c:0;return a}function X(){this.Gb=null;this.ub=this.oc=0}X.prototype=new rf;X.prototype.constructor=X;function tf(){}tf.prototype=X.prototype;X.prototype.j=function(){return this.Gb.j().xb(this.oc)};
X.prototype.q=function(){var a=this.Gb.q();return 0<=a?(a=a-this.ub|0,0<a?a:0):-1};X.prototype.g=function(){return!this.j().o()};X.prototype.$classData=x({Uc:0},"scala.collection.View$Drop",{Uc:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1});function uf(){}uf.prototype=new ff;uf.prototype.constructor=uf;function vf(){}d=vf.prototype=uf.prototype;d.bc=function(){return!0};d.J=function(a){return sf(this,a)};d.Z=function(){return qd(this)};d.y=function(){return xb(this,this.ua()+"(",", ")};
d.T=function(a){return zd(this,a)};d.g=function(){return be(this)};d.nb=function(a){return ce(this,a)};function wf(){}wf.prototype=new rf;wf.prototype.constructor=wf;function xf(){}d=xf.prototype=wf.prototype;d.lb=function(a){return yf(new zf,this,a)};d.V=function(){return"SeqView"};d.T=function(a){return zd(this,a)};d.g=function(){return be(this)};d.P=function(a){return this.lb(a)};function yf(a,b,c){a.mc=b;gf(a,b,c);return a}function zf(){this.Gb=null;this.ub=this.oc=0;this.mc=null}
zf.prototype=new tf;zf.prototype.constructor=zf;function Af(){}d=Af.prototype=zf.prototype;d.lb=function(a){return yf(new zf,this,a)};d.V=function(){return"SeqView"};d.T=function(a){return zd(this,a)};d.g=function(){return be(this)};d.l=function(){var a=this.mc.l()-this.ub|0;return 0<a?a:0};d.t=function(a){return this.mc.t(a+this.ub|0)};d.P=function(a){return this.lb(a)};d.$classData=x({Gd:0},"scala.collection.SeqView$Drop",{Gd:1,Uc:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1,Eb:1,Q:1});
function Ld(a,b){a.db=b;return a}function Md(){this.db=null}Md.prototype=new xf;Md.prototype.constructor=Md;function Bf(){}d=Bf.prototype=Md.prototype;d.t=function(a){return this.db.t(a)};d.l=function(){return this.db.l()};d.j=function(){return this.db.j()};d.q=function(){return this.db.q()};d.g=function(){return this.db.g()};d.$classData=x({Hd:0},"scala.collection.SeqView$Id",{Hd:1,Qc:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1,Eb:1,Q:1});function Cf(){}Cf.prototype=new xf;
Cf.prototype.constructor=Cf;function Df(){}d=Df.prototype=Cf.prototype;d.j=function(){return new Y(this)};d.V=function(){return"IndexedSeqView"};d.T=function(a){var b=this.l();return b===a?0:b<a?-1:1};d.q=function(){return this.l()};d.lb=function(a){return new V(this,a)};d.P=function(a){return new V(this,a)};function V(a,b){this.Gb=null;this.ub=this.oc=0;this.mc=null;yf(this,a,b)}V.prototype=new Af;V.prototype.constructor=V;d=V.prototype;d.j=function(){return new Y(this)};d.V=function(){return"IndexedSeqView"};
d.T=function(a){var b=this.l();return b===a?0:b<a?-1:1};d.q=function(){return this.l()};d.lb=function(a){return new V(this,a)};d.P=function(a){return new V(this,a)};d.$classData=x({df:0},"scala.collection.IndexedSeqView$Drop",{df:1,Gd:1,Uc:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1,Eb:1,Q:1,Rc:1,Fa:1});function Ef(a){this.db=null;Ld(this,a)}Ef.prototype=new Bf;Ef.prototype.constructor=Ef;d=Ef.prototype;d.j=function(){return new Y(this)};d.V=function(){return"IndexedSeqView"};
d.T=function(a){var b=this.l();return b===a?0:b<a?-1:1};d.q=function(){return this.l()};d.lb=function(a){return new V(this,a)};d.P=function(a){return new V(this,a)};d.$classData=x({ef:0},"scala.collection.IndexedSeqView$Id",{ef:1,Hd:1,Qc:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1,Eb:1,Q:1,Rc:1,Fa:1});function Ff(){}Ff.prototype=new vf;Ff.prototype.constructor=Ff;function Gf(){}Gf.prototype=Ff.prototype;function Hf(a,b){this.Qf=a;this.$c=b}Hf.prototype=new Df;Hf.prototype.constructor=Hf;
Hf.prototype.l=function(){return this.$c};Hf.prototype.t=function(a){if(a<this.$c)return this.Qf.a[a];throw G(a+" is out of bounds (min 0, max "+(-1+this.$c|0)+")");};Hf.prototype.ua=function(){return"ArrayBufferView"};Hf.prototype.$classData=x({Pf:0},"scala.collection.mutable.ArrayBufferView",{Pf:1,cf:1,Qc:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1,Eb:1,Q:1,Rc:1,Fa:1});function If(a,b){return Ae(b)?a.l()===b.l():!0}
function Jf(a,b){if(Ae(b)){if(a===b)return!0;var c=a.l(),e=c===b.l();if(e){var f=0,g=a.$b(),h=b.$b();g=g<h?g:h;h=c>>31;var k=g>>>31|0|g>>31<<1;for(g=(h===k?(-2147483648^c)>(-2147483648^g<<1):h>k)?g:c;f<g&&e;)e=D(E(),a.t(f),b.t(f)),f=1+f|0;if(f<c&&e)for(a=a.j().xb(f),b=b.j().xb(f);e&&a.o();)e=D(E(),a.p(),b.p())}return e}return ce(a,b)}function Ae(a){return!!(a&&a.$classData&&a.$classData.ca.Vc)}function Kf(a){this.tb=a}Kf.prototype=new Df;Kf.prototype.constructor=Kf;d=Kf.prototype;
d.l=function(){return this.tb.length|0};d.y=function(){return"StringView("+this.tb+")"};d.Ca=function(){return"StringView"};d.Qa=function(){return 1};d.Ra=function(a){return 0===a?this.tb:Wb(H(),a)};d.Z=function(){return dc(this)};d.J=function(a){return this===a?!0:a instanceof Kf?this.tb===a.tb:!1};d.t=function(a){return new m(65535&(this.tb.charCodeAt(a)|0))};d.$classData=x({pf:0},"scala.collection.StringView",{pf:1,cf:1,Qc:1,bb:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,Wa:1,c:1,Eb:1,Q:1,Rc:1,Fa:1,Sa:1,F:1});
function Lf(){}Lf.prototype=new vf;Lf.prototype.constructor=Lf;function Mf(){}Mf.prototype=Lf.prototype;
function Nf(a,b,c,e,f){b.e=""+b.e+c;if(!a.na)b.e+="\x3cnot computed\x3e";else if(!a.g()){c=T(a).z();b.e=""+b.e+c;c=a;var g=T(a).E();if(c!==g&&(!g.na||T(c)!==T(g))&&(c=g,g.na&&!g.g()))for(g=T(g).E();c!==g&&g.na&&!g.g()&&T(c)!==T(g);){b.e=""+b.e+e;var h=T(c).z();b.e=""+b.e+h;c=T(c).E();g=T(g).E();g.na&&!g.g()&&(g=T(g).E())}if(!g.na||g.g()){for(;c!==g;)b.e=""+b.e+e,a=T(c).z(),b.e=""+b.e+a,c=T(c).E();c.na||(b.e=""+b.e+e,b.e+="\x3cnot computed\x3e")}else{h=a;for(a=0;;){var k=h,p=g;if(k!==p&&T(k)!==T(p))h=
T(h).E(),g=T(g).E(),a=1+a|0;else break}h=c;k=g;(h===k||T(h)===T(k))&&0<a&&(b.e=""+b.e+e,a=T(c).z(),b.e=""+b.e+a,c=T(c).E());for(;;)if(a=c,h=g,a!==h&&T(a)!==T(h))b.e=""+b.e+e,a=T(c).z(),b.e=""+b.e+a,c=T(c).E();else break;b.e=""+b.e+e;b.e+="\x3ccycle\x3e"}}b.e=""+b.e+f;return b}function S(a){this.Md=null;this.Xc=!1;this.Ld=a;this.na=!1}S.prototype=new Gf;S.prototype.constructor=S;d=S.prototype;d.V=function(){return"LinearSeq"};d.l=function(){for(var a=this,b=0;!a.g();)b=1+b|0,a=a.M();return b};
d.T=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.g()?0:1;break a}if(b.g()){a=-1;break a}c=1+c|0;b=b.M()}return a};d.t=function(a){return L(this,a)};d.nb=function(a){return we(this,a)};function T(a){if(!a.Xc&&!a.Xc){var b=Td(a.Ld);a.na=!0;a.Ld=null;a.Md=b;a.Xc=!0}return a.Md}d.g=function(){return T(this)===Sd()};d.q=function(){return this.na&&this.g()?0:-1};d.z=function(){return T(this).z()};
function fe(a){var b=a,c=a;for(b.g()||(b=T(b).E());c!==b&&!b.g();){b=T(b).E();if(b.g())break;b=T(b).E();if(b===c)break;c=T(c).E()}return a}d.j=function(){return this.na&&this.g()?Fd().Ua:new Ce(this)};d.ua=function(){return"LazyList"};d.J=function(a){return this===a||sf(this,a)};d.Zb=function(a,b,c,e){fe(this);Nf(this,a.L,b,c,e);return a};d.y=function(){var a=new Xd;Wd(a);a.e="LazyList";return Nf(this,a,"(",", ",")").e};d.ta=function(a){return L(this,a|0)};
d.P=function(a){return 0>=a?this:this.na&&this.g()?Kd().Wc:ge(Kd(),this,a)};d.M=function(){return T(this).E()};d.za=function(){return Kd()};d.$classData=x({wf:0},"scala.collection.immutable.LazyList",{wf:1,qc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,Kb:1,Ib:1,Lb:1,Nd:1,Tc:1,Fd:1,Od:1,c:1});function le(a){this.ja=a}le.prototype=new Gf;le.prototype.constructor=le;d=le.prototype;d.bc=function(a){return If(this,a)};d.V=function(){return"IndexedSeq"};d.j=function(){return new Y(new Kf(this.ja))};
d.P=function(a){return ve(this,a)};d.T=function(a){var b=this.ja.length|0;return b===a?0:b<a?-1:1};d.q=function(){return this.ja.length|0};d.l=function(){return this.ja.length|0};d.y=function(){return this.ja};d.nb=function(a){return a instanceof le?this.ja===a.ja:Jf(this,a)};d.ua=function(){return"WrappedString"};d.$b=function(){return 2147483647};d.J=function(a){return a instanceof le?this.ja===a.ja:sf(this,a)};d.za=function(){Be||(Be=new ye);return Be};d.yb=function(a){return ke(me(),a)};
d.Hc=function(a){return ke(me(),a)};d.ta=function(a){return new m(65535&(this.ja.charCodeAt(a|0)|0))};d.t=function(a){return new m(65535&(this.ja.charCodeAt(a)|0))};d.$classData=x({Lf:0},"scala.collection.immutable.WrappedString",{Lf:1,qc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,Kb:1,Ib:1,Lb:1,Vc:1,pb:1,Fa:1,Kd:1,c:1});function ud(a){this.he=a}ud.prototype=new y;ud.prototype.constructor=ud;d=ud.prototype;d.bc=function(a){return If(this,a)};d.nb=function(a){return Jf(this,a)};
d.$b=function(){Bb||(Bb=new Ab);return Bb.Jd};d.j=function(){var a=new Ef(this);return new Y(a)};d.P=function(a){return ve(this,a)};d.T=function(a){var b=this.l();return b===a?0:b<a?-1:1};d.q=function(){return this.l()};d.J=function(a){return sf(this,a)};d.Z=function(){return qd(this)};d.y=function(){return xb(this,this.ua()+"(",", ")};d.g=function(){return be(this)};d.z=function(){var a=new Ef(this);return(new Y(a)).p()};d.M=function(){return Ad(this)};
d.Zb=function(a,b,c,e){return zb(this,a,b,c,e)};d.l=function(){return this.he.length|0};d.t=function(a){return this.he[a]};d.ua=function(){return"WrappedVarArgs"};d.yb=function(a){bf||(bf=new af);return bf.ic().Oa(a).Da()};d.ta=function(a){return this.t(a|0)};d.$classData=x({dg:0},"scala.scalajs.runtime.WrappedVarArgs",{dg:1,b:1,Vc:1,Kb:1,Ib:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,Lb:1,pb:1,Fa:1,Kd:1,Yc:1,sb:1,rb:1,c:1});function Of(){}Of.prototype=new Mf;Of.prototype.constructor=Of;
function Pf(){}Pf.prototype=Of.prototype;Of.prototype.Oa=function(a){return fd(this,a)};function rd(){}rd.prototype=new Gf;rd.prototype.constructor=rd;function Qf(){}d=Qf.prototype=rd.prototype;d.j=function(){return new xe(this)};d.V=function(){return"LinearSeq"};d.t=function(a){return L(this,a)};d.nb=function(a){return we(this,a)};d.g=function(){return this===M()};d.l=function(){for(var a=this,b=0;!a.g();)b=1+b|0,a=a.M();return b};
d.T=function(a){if(0>a)a=1;else a:for(var b=this,c=0;;){if(c===a){a=b.g()?0:1;break a}if(b.g()){a=-1;break a}c=1+c|0;b=b.M()}return a};d.ua=function(){return"List"};d.J=function(a){var b;if(a instanceof rd)a:for(b=this;;){if(b===a){b=!0;break a}var c=b.g(),e=a.g();if(c||e||!D(E(),b.z(),a.z())){b=c&&e;break a}b=b.M();a=a.M()}else b=sf(this,a);return b};d.ta=function(a){return L(this,a|0)};d.P=function(a){a:for(var b=this;;){if(0>=a||b.g())break a;a=-1+a|0;b=b.M()}return b};
d.za=function(){Ee||(Ee=new De);return Ee};
function Rf(a,b,c){if(32>c)return a.ia.a[31&b];if(1024>c)return a.R.a[31&(b>>>5|0)].a[31&b];if(32768>c)return a.ba.a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];if(1048576>c)return a.pa.a[31&(b>>>15|0)].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];if(33554432>c)return a.Ga.a[31&(b>>>20|0)].a[31&(b>>>15|0)].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];if(1073741824>c)return a.fb.a[31&(b>>>25|0)].a[31&(b>>>20|0)].a[31&(b>>>15|0)].a[31&(b>>>10|0)].a[31&(b>>>5|0)].a[31&b];throw Gb();}
function Sf(a,b){for(var c=0;c<b;)a.a[c]=null,c=1+c|0}function Z(a,b){a=a.k();rb||(rb=new qb);if(0>b)throw Sb("fromIndex(0) \x3e toIndex("+b+")");for(var c=0;c!==b;)a.a[c]=null,c=1+c|0;return a}function Tf(a){if(32>a)return 1;if(1024>a)return 2;if(32768>a)return 3;if(1048576>a)return 4;if(33554432>a)return 5;if(1073741824>a)return 6;throw Gb();}function W(a,b,c){this.Pb=0;this.fb=this.Ga=this.pa=this.ba=this.R=this.ia=null;this.Ia=a;this.Ha=b;this.Rb=c;this.Qb=!1}W.prototype=new Gf;
W.prototype.constructor=W;d=W.prototype;d.bc=function(a){return If(this,a)};d.nb=function(a){return Jf(this,a)};d.V=function(){return"IndexedSeq"};d.T=function(a){var b=this.l();return b===a?0:b<a?-1:1};d.q=function(){return this.l()};d.S=function(){return this.Pb};d.ya=function(a){this.Pb=a};d.u=function(){return this.ia};d.m=function(a){this.ia=a};d.d=function(){return this.R};d.i=function(a){this.R=a};d.f=function(){return this.ba};d.n=function(a){this.ba=a};d.h=function(){return this.pa};
d.s=function(a){this.pa=a};d.r=function(){return this.Ga};d.A=function(a){this.Ga=a};d.O=function(){return this.fb};d.da=function(a){this.fb=a};d.l=function(){return this.Ha-this.Ia|0};
d.j=function(){if(be(this))return Fd().Ua;var a=new kf(this.Ia,this.Ha);Eb(a,this,this.Pb);if(this.Qb){var b=this.Rb,c=-1+a.S()|0;switch(c){case 5:a.da(a.O().k());a.A(a.r().k());a.s(a.h().k());a.n(a.f().k());a.i(a.d().k());a.O().a[31&(b>>>25|0)]=a.r();a.r().a[31&(b>>>20|0)]=a.h();a.h().a[31&(b>>>15|0)]=a.f();a.f().a[31&(b>>>10|0)]=a.d();a.d().a[31&(b>>>5|0)]=a.u();break;case 4:a.A(a.r().k());a.s(a.h().k());a.n(a.f().k());a.i(a.d().k());a.r().a[31&(b>>>20|0)]=a.h();a.h().a[31&(b>>>15|0)]=a.f();a.f().a[31&
(b>>>10|0)]=a.d();a.d().a[31&(b>>>5|0)]=a.u();break;case 3:a.s(a.h().k());a.n(a.f().k());a.i(a.d().k());a.h().a[31&(b>>>15|0)]=a.f();a.f().a[31&(b>>>10|0)]=a.d();a.d().a[31&(b>>>5|0)]=a.u();break;case 2:a.n(a.f().k());a.i(a.d().k());a.f().a[31&(b>>>10|0)]=a.d();a.d().a[31&(b>>>5|0)]=a.u();break;case 1:a.i(a.d().k());a.d().a[31&(b>>>5|0)]=a.u();break;case 0:break;default:throw new B(c);}}1<a.sc&&Fb(a,this.Ia,this.Ia^this.Rb);return a};
d.t=function(a){var b=a+this.Ia|0;if(0<=a&&b<this.Ha)a=b;else throw G(a+" is out of bounds (min 0, max "+(-1+this.Ha|0)+")");return Rf(this,a,a^this.Rb)};
function Uf(a,b){if(0>=b)b=a;else if(a.Ia<(a.Ha-b|0)){var c=a.Ia+b|0,e=-32&c,f=Tf(c^(-1+a.Ha|0)),g=c&~(-1+(1<<l(5,f))|0);b=new W(c-g|0,a.Ha-g|0,e-g|0);Eb(b,a,a.Pb);b.Qb=a.Qb;if(b.Qb){var h=a.Rb;a=a.Rb^e;if(32>a)b.m(b.u().k());else if(1024>a)b.i(b.d().k()),b.d().a[31&(h>>>5|0)]=b.u(),b.m(C(b.d(),31&(e>>>5|0)));else if(32768>a)b.i(b.d().k()),b.n(b.f().k()),b.d().a[31&(h>>>5|0)]=b.u(),b.f().a[31&(h>>>10|0)]=b.d(),b.i(C(b.f(),31&(e>>>10|0))),b.m(C(b.d(),31&(e>>>5|0)));else if(1048576>a)b.i(b.d().k()),
b.n(b.f().k()),b.s(b.h().k()),b.d().a[31&(h>>>5|0)]=b.u(),b.f().a[31&(h>>>10|0)]=b.d(),b.h().a[31&(h>>>15|0)]=b.f(),b.n(C(b.h(),31&(e>>>15|0))),b.i(C(b.f(),31&(e>>>10|0))),b.m(C(b.d(),31&(e>>>5|0)));else if(33554432>a)b.i(b.d().k()),b.n(b.f().k()),b.s(b.h().k()),b.A(b.r().k()),b.d().a[31&(h>>>5|0)]=b.u(),b.f().a[31&(h>>>10|0)]=b.d(),b.h().a[31&(h>>>15|0)]=b.f(),b.r().a[31&(h>>>20|0)]=b.h(),b.s(C(b.r(),31&(e>>>20|0))),b.n(C(b.h(),31&(e>>>15|0))),b.i(C(b.f(),31&(e>>>10|0))),b.m(C(b.d(),31&(e>>>5|0)));
else if(1073741824>a)b.i(b.d().k()),b.n(b.f().k()),b.s(b.h().k()),b.A(b.r().k()),b.da(b.O().k()),b.d().a[31&(h>>>5|0)]=b.u(),b.f().a[31&(h>>>10|0)]=b.d(),b.h().a[31&(h>>>15|0)]=b.f(),b.r().a[31&(h>>>20|0)]=b.h(),b.O().a[31&(h>>>25|0)]=b.r(),b.A(C(b.O(),31&(e>>>25|0))),b.s(C(b.r(),31&(e>>>20|0))),b.n(C(b.h(),31&(e>>>15|0))),b.i(C(b.f(),31&(e>>>10|0))),b.m(C(b.d(),31&(e>>>5|0)));else throw Gb();}else{a=-1+b.S()|0;switch(a){case 5:b.da(b.O().k());b.A(C(b.O(),31&(e>>>25|0)));b.s(C(b.r(),31&(e>>>20|0)));
b.n(C(b.h(),31&(e>>>15|0)));b.i(C(b.f(),31&(e>>>10|0)));b.m(C(b.d(),31&(e>>>5|0)));break;case 4:b.A(b.r().k());b.s(C(b.r(),31&(e>>>20|0)));b.n(C(b.h(),31&(e>>>15|0)));b.i(C(b.f(),31&(e>>>10|0)));b.m(C(b.d(),31&(e>>>5|0)));break;case 3:b.s(b.h().k());b.n(C(b.h(),31&(e>>>15|0)));b.i(C(b.f(),31&(e>>>10|0)));b.m(C(b.d(),31&(e>>>5|0)));break;case 2:b.n(b.f().k());b.i(C(b.f(),31&(e>>>10|0)));b.m(C(b.d(),31&(e>>>5|0)));break;case 1:b.i(b.d().k());b.m(C(b.d(),31&(e>>>5|0)));break;case 0:b.m(b.u().k());break;
default:throw new B(a);}b.Qb=!0}b.ya(f);e=-1+f|0;switch(e){case 0:b.i(null);b.n(null);b.s(null);b.A(null);b.da(null);break;case 1:b.n(null);b.s(null);b.A(null);b.da(null);break;case 2:b.s(null);b.A(null);b.da(null);break;case 3:b.A(null);b.da(null);break;case 4:b.da(null);break;case 5:break;default:throw new B(e);}c=c-g|0;if(32>c)Sf(b.ia,c);else if(1024>c)Sf(b.ia,31&c),b.R=Z(b.R,c>>>5|0);else if(32768>c)Sf(b.ia,31&c),b.R=Z(b.R,31&(c>>>5|0)),b.ba=Z(b.ba,c>>>10|0);else if(1048576>c)Sf(b.ia,31&c),b.R=
Z(b.R,31&(c>>>5|0)),b.ba=Z(b.ba,31&(c>>>10|0)),b.pa=Z(b.pa,c>>>15|0);else if(33554432>c)Sf(b.ia,31&c),b.R=Z(b.R,31&(c>>>5|0)),b.ba=Z(b.ba,31&(c>>>10|0)),b.pa=Z(b.pa,31&(c>>>15|0)),b.Ga=Z(b.Ga,c>>>20|0);else if(1073741824>c)Sf(b.ia,31&c),b.R=Z(b.R,31&(c>>>5|0)),b.ba=Z(b.ba,31&(c>>>10|0)),b.pa=Z(b.pa,31&(c>>>15|0)),b.Ga=Z(b.Ga,31&(c>>>20|0)),b.fb=Z(b.fb,c>>>25|0);else throw Gb();}else b=ze().rc;return b}d.z=function(){if(be(this))throw new Q("empty.head");return this.t(0)};d.$b=function(){return ze().Pd};
d.J=function(a){return a instanceof W?this===a||this.l()===a.l()&&(this.Ia===a.Ia&&this.Ha===a.Ha&&this.ia===a.ia&&this.R===a.R&&this.ba===a.ba&&this.pa===a.pa&&this.Ga===a.Ga&&this.fb===a.fb||sf(this,a)):sf(this,a)};d.ua=function(){return"Vector"};d.M=function(){if(be(this))throw Qd("empty.tail");return Uf(this,1)};d.P=function(a){return Uf(this,a)};d.ta=function(a){return this.t(a|0)};d.za=function(){return ze()};
d.$classData=x({Hf:0},"scala.collection.immutable.Vector",{Hf:1,qc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,Kb:1,Ib:1,Lb:1,Vc:1,pb:1,Fa:1,Kd:1,Yc:1,sb:1,rb:1,$d:1,pc:1,c:1});function Vf(a,b){this.Id=a;this.Hb=b}Vf.prototype=new Qf;Vf.prototype.constructor=Vf;d=Vf.prototype;d.z=function(){return this.Id};d.Ca=function(){return"::"};d.Qa=function(){return 2};d.Ra=function(a){switch(a){case 0:return this.Id;case 1:return this.Hb;default:return Wb(H(),a)}};d.M=function(){return this.Hb};
d.$classData=x({tf:0},"scala.collection.immutable.$colon$colon",{tf:1,Ef:1,qc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,Kb:1,Ib:1,Lb:1,Nd:1,Tc:1,Fd:1,Od:1,nf:1,sb:1,rb:1,Yc:1,pc:1,c:1,Sa:1});function Wf(){Xf=this;M();M()}Wf.prototype=new Qf;Wf.prototype.constructor=Wf;d=Wf.prototype;d.Ic=function(){throw new Q("head of empty list");};d.q=function(){return 0};d.j=function(){return Fd().Ua};d.Ca=function(){return"Nil"};d.Qa=function(){return 0};d.Ra=function(a){return Wb(H(),a)};
d.M=function(){throw Qd("tail of empty list");};d.z=function(){this.Ic()};d.$classData=x({Gf:0},"scala.collection.immutable.Nil$",{Gf:1,Ef:1,qc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,Kb:1,Ib:1,Lb:1,Nd:1,Tc:1,Fd:1,Od:1,nf:1,sb:1,rb:1,Yc:1,pc:1,c:1,Sa:1});var Xf=void 0;function M(){Xf||(Xf=new Wf);return Xf}function yb(){var a=new Yf;a.L=Wd(new Xd);return a}function Yf(){this.L=null}Yf.prototype=new Mf;Yf.prototype.constructor=Yf;d=Yf.prototype;d.V=function(){return"IndexedSeq"};
d.j=function(){var a=new Ef(this);return new Y(a)};d.P=function(a){return ve(this,a)};d.T=function(a){var b=this.L.l();return b===a?0:b<a?-1:1};d.Oa=function(a){return fd(this,a)};d.l=function(){return this.L.l()};d.q=function(){return this.L.l()};d.y=function(){return this.L.e};
function Zf(a,b){if(b instanceof le){var c=a.L;me();c.e=""+c.e+b.ja}else if(b instanceof Yf)c=a.L,c.e=""+c.e+b.L;else{var e=b.q();if(0!==e)for(c=a.L,0<e&&c.l(),b=b.j();b.o();)e=t(b.p()),e=String.fromCharCode(e),c.e=""+c.e+e}return a}d.za=function(){Te||(Te=new Se);return Te};d.Da=function(){return this.L.e};d.Za=function(a){var b=this.L;a=String.fromCharCode(t(a));b.e=""+b.e+a};d.yb=function(a){return Zf(yb(),a)};d.Hc=function(a){return Zf(yb(),a)};
d.ta=function(a){return new m(65535&(this.L.e.charCodeAt(a|0)|0))};d.t=function(a){return new m(65535&(this.L.e.charCodeAt(a)|0))};d.$classData=x({Wf:0},"scala.collection.mutable.StringBuilder",{Wf:1,Zc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,cd:1,bd:1,dd:1,ad:1,gc:1,fe:1,uc:1,Tb:1,Sb:1,de:1,pb:1,Fa:1,ee:1,td:1,c:1});function $f(a){var b=vc(new N,a);a.ka=b.ka;a.Ja=b.Ja;a.Ub=!1}function N(){this.Ja=this.ka=null;this.Ub=!1;this.U=0;this.ka=M();this.Ja=null;this.Ub=!1;this.U=0}
N.prototype=new Pf;N.prototype.constructor=N;d=N.prototype;d.j=function(){return this.ka.j()};d.t=function(a){return L(this.ka,a)};d.l=function(){return this.U};d.q=function(){return this.U};d.g=function(){return 0===this.U};function Fe(a){a.Ub=!a.g();return a.ka}function vd(a,b){a.Ub&&$f(a);b=new Vf(b,M());0===a.U?a.ka=b:a.Ja.Hb=b;a.Ja=b;a.U=1+a.U|0}
function vc(a,b){b=b.j();if(b.o()){a.Ub&&$f(a);var c=new Vf(b.p(),M());0===a.U?a.ka=c:a.Ja.Hb=c;a.Ja=c;for(a.U=1+a.U|0;b.o();)c=new Vf(b.p(),M()),a.Ja.Hb=c,a.Ja=c,a.U=1+a.U|0}return a}d.V=function(){return"ListBuffer"};d.Oa=function(a){return vc(this,a)};d.Za=function(a){vd(this,a)};d.Da=function(){return Fe(this)};d.ta=function(a){return L(this.ka,a|0)};d.za=function(){Ve||(Ve=new Ue);return Ve};
d.$classData=x({Uf:0},"scala.collection.mutable.ListBuffer",{Uf:1,ae:1,Zc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,cd:1,bd:1,dd:1,ad:1,gc:1,be:1,Tb:1,Sb:1,ge:1,sb:1,rb:1,fe:1,uc:1,pc:1,c:1});function Pe(){this.qa=null;this.w=0}Pe.prototype=new Pf;Pe.prototype.constructor=Pe;d=Pe.prototype;d.j=function(){return new Y(new Hf(this.qa,this.w))};d.P=function(a){return ve(this,a)};d.T=function(a){var b=this.w;return b===a?0:b<a?-1:1};d.q=function(){return this.w};
d.t=function(a){var b=1+a|0;if(0>a)throw G(a+" is out of bounds (min 0, max "+(-1+this.w|0)+")");if(b>this.w)throw G(b+" is out of bounds (min 0, max "+(-1+this.w|0)+")");return this.qa.a[a]};d.l=function(){return this.w};d.V=function(){return"ArrayBuffer"};
d.Za=function(a){var b=this.w,c=1+this.w|0;this.qa=Oe(Qe(),this.qa,this.w,c);this.w=1+this.w|0;c=1+b|0;if(0>b)throw G(b+" is out of bounds (min 0, max "+(-1+this.w|0)+")");if(c>this.w)throw G(c+" is out of bounds (min 0, max "+(-1+this.w|0)+")");this.qa.a[b]=a};d.za=function(){return Qe()};d.ta=function(a){return this.t(a|0)};
d.$classData=x({Nf:0},"scala.collection.mutable.ArrayBuffer",{Nf:1,ae:1,Zc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,cd:1,bd:1,dd:1,ad:1,gc:1,be:1,Tb:1,Sb:1,ge:1,Sf:1,de:1,pb:1,Fa:1,ee:1,sb:1,rb:1,pc:1,c:1});function Ze(a){a.Ya=[];return a}function Ye(){this.Ya=null}Ye.prototype=new Pf;Ye.prototype.constructor=Ye;d=Ye.prototype;d.V=function(){return"IndexedSeq"};d.j=function(){var a=new Ef(this);return new Y(a)};d.P=function(a){return ve(this,a)};
d.T=function(a){var b=this.Ya.length|0;return b===a?0:b<a?-1:1};d.t=function(a){return this.Ya[a]};d.l=function(){return this.Ya.length|0};d.q=function(){return this.Ya.length|0};d.ua=function(){return"WrappedArray"};d.Da=function(){return this};d.Za=function(a){this.Ya.push(a)};d.ta=function(a){return this.Ya[a|0]};d.za=function(){$e||($e=new Xe);return $e};
d.$classData=x({Yf:0},"scala.scalajs.js.WrappedArray",{Yf:1,ae:1,Zc:1,Ta:1,K:1,b:1,C:1,v:1,H:1,x:1,G:1,xa:1,Ea:1,ra:1,Q:1,F:1,cd:1,bd:1,dd:1,ad:1,gc:1,be:1,Tb:1,Sb:1,ge:1,sb:1,rb:1,de:1,pb:1,Fa:1,ee:1,Sf:1,uc:1,c:1});da=new r(0,0);fa(z(ka),[]);gc||(gc=new fc);var ag=(new uc(15)).yc;tc(ag);
}).call(this);
//# sourceMappingURL=scalajsfun-opt.js.map
