(function(){
'use strict';var h;Object.freeze({assumingES6:!1,productionMode:!0,linkerVersion:"1.0.1",fileLevelThis:this});var l=Math.imul||function(a,b){var d=a&65535,c=b&65535;return d*c+((a>>>16)*c+d*(b>>>16)<<16>>>0)|0},aa=Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&-65536)&&(a<<=16,b+=16);0===(a&-16777216)&&(a<<=8,b+=8);0===(a&-268435456)&&(a<<=4,b+=4);0===(a&-1073741824)&&(a<<=2,b+=2);return b+(a>>31)},ba;function ca(a){for(var b in a)return b}function da(a){this.Aa=a}
da.prototype.toString=function(){return String.fromCharCode(this.Aa)};function m(a,b){return new a.fa(b)}var fa=function ea(a,b,d){var e=new a.fa(b[d]);if(d<b.length-1){a=a.Ba;d+=1;for(var g=e.b,f=0;f<g.length;f++)g[f]=ea(a,b,d)}return e};
function ha(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Sb():a instanceof n?"java.lang.Long":a instanceof da?"java.lang.Character":a&&a.$classData?a.$classData.name:null.Tb()}}
function ia(a){return void 0===a?"undefined":a.toString()}function ja(a){switch(typeof a){case "string":return q(a);case "number":return a=+a,ka(la(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.l():a instanceof da?null===a?0:a.Aa:ma(a)}}function na(a){return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}
var oa=0,pa="undefined"!==typeof WeakMap?new WeakMap:null,ma=null!==pa?function(a){switch(typeof a){case "string":case "number":case "bigint":case "boolean":case "undefined":return ja(a);default:if(null===a)return 0;var b=pa.get(a);void 0===b&&(oa=b=oa+1|0,pa.set(a,b));return b}}:function(a){switch(typeof a){case "string":case "number":case "bigint":case "boolean":case "undefined":return ja(a);default:if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(Object.isSealed(a))return 42;
oa=b=oa+1|0;return a.$idHashCode$0=b}null===a?0:42}};function qa(){this.fa=void 0;this.f=this.Ba=this.B=null;this.g=0;this.ra=null;this.R="";this.ha=this.ea=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function r(a,b,d,c){var e=new qa;e.B={};e.ra=a;e.R=b;e.ha=c;e.name=d;e.isPrimitive=!0;e.isInstance=function(){return!1};return e}
function u(a,b,d,c,e){var g=new qa,f=ca(a);g.B=d;g.R="L"+b+";";g.ha=e||function(k,p){return!!(k&&k.$classData&&k.$classData.g===p&&k.$classData.f.B[f])};g.name=b;g.isInterface=!1;g.isInstance=c||function(k){return!!(k&&k.$classData&&k.$classData.B[f])};return g}
function ra(a){function b(k){if("number"===typeof k){this.b=Array(k);for(var p=0;p<k;p++)this.b[p]=c}else this.b=k}var d=new qa,c="longZero"===a.ra?ba:a.ra;b.prototype=new v;b.prototype.constructor=b;b.prototype.$classData=d;var e="["+a.R,g=a.f||a,f=a.g+1;d.fa=b;d.B={a:1,hb:1,c:1};d.Ba=a;d.f=g;d.g=f;d.R=e;d.name=e;d.isArrayClass=!0;d.isInstance=function(k){return g.ha(k,f)};return d}function y(a){a.ea||(a.ea=ra(a));return a.ea}
function sa(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==ta)}function ua(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==va)}function wa(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==xa)}function ya(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Aa)}function Ba(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Ca)}
function Da(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Ea)}function Fa(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Ga)}function Ha(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Ia)}var ta=r(!1,"Z","boolean",sa),va=r(0,"C","char",ua),xa=r(0,"B","byte",wa),Aa=r(0,"S","short",ya),Ca=r(0,"I","int",Ba),Ea=r("longZero","J","long",Da),Ga=r(0,"F","float",Fa),Ia=r(0,"D","double",Ha);function z(){}function v(){}v.prototype=z.prototype;
z.prototype.l=function(){return ma(this)};z.prototype.k=function(){var a=ha(this),b=this.l();return a+"@"+(+(b>>>0)).toString(16)};z.prototype.toString=function(){return this.k()};z.prototype.$classData=u({a:0},"java.lang.Object",{a:1},function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var d=a.g||0;return!(d<b)&&(d>b||!a.f.isPrimitive)}return!1});
function Ja(){this.v=!1;this.Fa=this.T=this.H=null;this.ia=!1;this.Ha=this.Ga=0;Ka=this;this.H=(this.v="undefined"!==typeof ArrayBuffer&&"undefined"!==typeof Int32Array&&"undefined"!==typeof Float32Array&&"undefined"!==typeof Float64Array)?new ArrayBuffer(8):null;this.T=this.v?new Int32Array(this.H,0,2):null;this.v&&new Float32Array(this.H,0,2);this.Fa=this.v?new Float64Array(this.H,0,1):null;if(this.v)this.T[0]=16909060,a=1===((new Int8Array(this.H,0,8))[0]|0);else var a=!0;this.Ga=(this.ia=a)?0:
1;this.Ha=this.ia?1:0}Ja.prototype=new v;Ja.prototype.constructor=Ja;
function ka(a,b){var d=b|0;if(d===b&&-Infinity!==1/b)return d;if(a.v)a.Fa[0]=b,a=new n(a.T[a.Ha]|0,a.T[a.Ga]|0);else{if(b!==b)a=!1,b=2047,d=+Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,d=0;else if(0===b)a=-Infinity===1/b,d=b=0;else{var c=(a=0>b)?-b:b;if(c>=+Math.pow(2,-1022)){d=+Math.pow(2,52);b=+Math.floor(+Math.log(c)/.6931471805599453)|0;1023<b&&(b=1023);var e=+Math.pow(2,b);e>c&&(b=-1+b|0,e/=2);e=c/e*d;c=+Math.floor(e);e-=c;c=.5>e?c:.5<e?1+c:0!==c%2?1+c:c;2<=c/d&&(b=1+b|0,
c=1);1023<b?(b=2047,c=0):(b=1023+b|0,c-=d);d=c}else b=c/+Math.pow(2,-1074),d=+Math.floor(b),c=b-d,b=0,d=.5>c?d:.5<c?1+d:0!==d%2?1+d:d}a=new n(d|0,(a?-2147483648:0)|b<<20|d/4294967296|0)}return a.A^a.z}Ja.prototype.$classData=u({jb:0},"java.lang.FloatingPointBits$",{jb:1,a:1});var Ka=void 0;function la(){Ka||(Ka=new Ja);return Ka}function La(){this.sa=this.ta=null;this.n=0}La.prototype=new v;La.prototype.constructor=La;
function Ma(a){0===(33554432&a.n)&&0===(33554432&a.n)&&(a.ta=window,a.n|=33554432);return a.ta}function A(){var a=Na();0===(67108864&a.n)&&0===(67108864&a.n)&&(a.sa=Ma(a).document,a.n|=67108864);return a.sa}La.prototype.$classData=u({Ma:0},"org.scalajs.dom.package$",{Ma:1,a:1});var Oa=void 0;function Na(){Oa||(Oa=new La);return Oa}
function Pa(a,b,d,c,e){var g=b.x;0!==(d.length|0)&&(g.e=""+g.e+d);a=a.F();if(a.i())for(d=a.j(),g.e=""+g.e+d;a.i();)g.e=""+g.e+c,d=a.j(),g.e=""+g.e+d;0!==(e.length|0)&&(g.e=""+g.e+e);return b}function Qa(){}Qa.prototype=new v;Qa.prototype.constructor=Qa;Qa.prototype.$classData=u({Mb:0},"scala.runtime.ScalaRunTime$",{Mb:1,a:1});var Ra=void 0;function Sa(){}Sa.prototype=new v;Sa.prototype.constructor=Sa;
function B(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=na(a);if(b===a)a=b;else{b=Ta();if(-9223372036854775808>a){b.Q=-2147483648;var d=0}else if(0x7fffffffffffffff<=a)b.Q=2147483647,d=-1;else{d=a|0;var c=a/4294967296|0;b.Q=0>a&&0!==d?-1+c|0:c}b=b.Q;Ta();a=(0>b?-(4294967296*+((0!==d?~b:-b|0)>>>0)+ +((-d|0)>>>0)):4294967296*b+ +(d>>>0))===a?d^b:ka(la(),a)}return a}return b instanceof n?(a=null===b?ba:b,b=new n(a.A,a.z),a=b.A,b=b.z,b===a>>31?a:a^b):ja(b)}
Sa.prototype.$classData=u({Pb:0},"scala.runtime.Statics$",{Pb:1,a:1});var Ua=void 0;function C(){Ua||(Ua=new Sa);return Ua}function D(){}D.prototype=new v;D.prototype.constructor=D;D.prototype.$classData=u({Kb:0},"scala.scalajs.runtime.package$",{Kb:1,a:1});var Xa=void 0;function Ya(){}Ya.prototype=new v;Ya.prototype.constructor=Ya;Ya.prototype.$classData=u({sb:0},"scala.sys.package$",{sb:1,a:1});var Za=void 0;function $a(){}$a.prototype=new v;$a.prototype.constructor=$a;function ab(){}
ab.prototype=$a.prototype;function E(a,b){b=l(-862048943,b);b=l(461845907,b<<15|b>>>17|0);a^=b;return-430675100+l(5,a<<13|a>>>19|0)|0}function F(a){a=l(-2048144789,a^(a>>>16|0));a=l(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function bb(a){cb();var b=a.U();if(0===b)return q(a.J());var d=E(-889275714,q(a.J()));for(var c=0;c<b;){var e=a.V(c);d=E(d,B(C(),e));c=1+c|0}return F(d^b)}function G(a,b,d,c){this.y=a;this.ca=b;this.ba=d;this.Oa=c}G.prototype=new v;G.prototype.constructor=G;
G.prototype.ga=function(a){var b=a.va;b.beginPath();b.arc(this.y.t,this.y.u,this.Oa,0,6.283185307179586,!1);b.fillStyle="#00BB00";b.fill();b.lineWidth=2.5/a.ua;b.strokeStyle="#0000FF";b.stroke()};var H=u({Na:0},"scalajs.fun.gravity.Body",{Na:1,a:1});G.prototype.$classData=H;function db(a){this.va=a;this.ua=1}db.prototype=new v;db.prototype.constructor=db;db.prototype.$classData=u({Pa:0},"scalajs.fun.gravity.Graphics2D",{Pa:1,a:1});
function eb(a,b){if(null===a)throw new fb;a.L?a=a.M:(b=new gb(b),a.M=b,a.L=!0,a=b);return a}function I(){}I.prototype=new v;I.prototype.constructor=I;I.prototype.$classData=u({Qa:0},"scalajs.fun.gravity.Gravity$",{Qa:1,a:1});var hb=void 0;function gb(a){this.O=null;this.da=a;this.O=J()}gb.prototype=new v;gb.prototype.constructor=gb;
function ib(a,b){var d=a.O;a:if(J()===d)jb(a.da.b[b]),a.O=new K(b);else{if(d instanceof K){var c=d.X|0;if(b!==c){kb(a.da.b[c]);jb(a.da.b[b]);a.O=new K(b);break a}}throw new L(d);}}gb.prototype.$classData=u({Ya:0},"scalajs.fun.gravity.Gravity$Running$1$",{Ya:1,a:1});function lb(){this.d=null;this.h=0}lb.prototype=new v;lb.prototype.constructor=lb;function mb(){}mb.prototype=lb.prototype;
lb.prototype.ga=function(a){var b=this.d;a=function(g,f){return function(k){k.ga(f)}}(this,a);var d=b.b.length,c=0;if(null!==b)for(;c<d;)a(b.b[c]),c=1+c|0;else if(Ba(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(Ha(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(Da(b,1))for(;c<d;){var e=b.b[c];a(new n(e.A,e.z));c=1+c|0}else if(Fa(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(ua(b,1))for(;c<d;)a(new da(b.b[c])),c=1+c|0;else if(wa(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(ya(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(sa(b,
1))for(;c<d;)a(b.b[c]),c=1+c|0;else throw new L(b);};function M(a,b){this.t=a;this.u=b}M.prototype=new v;M.prototype.constructor=M;function nb(a,b){return new M(a.t*b,a.u*b)}function ob(a,b){return new M(a.t+b.t,a.u+b.u)}function pb(a){a=+Math.pow(a.t,2)+ +Math.pow(a.u,2);return+Math.sqrt(a)}var qb=u({Za:0},"scalajs.fun.gravity.Vector",{Za:1,a:1});M.prototype.$classData=qb;
function rb(a){var b=1E3/a.Sa;b=Ma(Na()).setInterval(function(d){return function(){d.N.setTransform(1,0,0,1,0,0);d.N.fillStyle="white";d.N.fillRect(0,0,d.Va,d.Ua);var c=d.ya,e=d.Ta;var g=y(qb);g=fa(g,[c.d.b.length],0);var f=g.b.length,k=-1+f|0;if(!(0>=f))for(f=0;;){g.b[f]=new M(0,0);if(f===k)break;f=1+f|0}f=g.b.length;k=-1+f|0;if(!(0>=f))for(f=0;;){var p=f,t=g.b.length,w=-1+t|0;if(!(0>=t))for(t=0;;){var x=t;if(p!==x){var uc=g.b,vc=p,wc=g.b[p],Va=c.d.b[p];x=c.d.b[x];var za=x.y;var Wa=Va.y;za=new M(za.t-
Wa.t,za.u-Wa.u);Wa=pb(za);Va=6.67E-11*Va.ba*x.ba/+Math.pow(Wa,2);x=za;if(0===pb(x))throw Za||(Za=new Ya),Xa||(Xa=new D),c=new sb,tb(c,"Nul vector has no direction"),c instanceof ub?c.qa:c;x=nb(x,1/pb(x));uc[vc]=ob(wc,nb(x,Va))}if(t===w)break;t=1+t|0}if(f===k)break;f=1+f|0}f=c.d.b.length;k=-1+f|0;if(!(0>=f))for(f=0;;){p=f;w=c.d.b[p];t=e;w.ca=ob(w.ca,nb(nb(g.b[p],1/w.ba),t));w.y=ob(w.y,nb(w.ca,t));if(f===k)break;f=1+f|0}d.N.translate(d.Wa,d.Xa);c=d.wa;e=d.xa;c.ua=e;c.va.scale(e,e);d.ya.ga(d.wa)}}(a),
b)|0;a.E=new K(b)}function jb(a){var b=a.E;if(J()===b)rb(a);else if(b instanceof K)kb(a),rb(a);else throw new L(b);}function kb(a){var b=a.E;if(J()!==b)if(b instanceof K)b=b.X|0,Ma(Na()).clearInterval(b),a.E=J();else throw new L(b);}function vb(){}vb.prototype=new v;vb.prototype.constructor=vb;function wb(){}wb.prototype=vb.prototype;function tb(a,b){a.m=b;a.p=null;a.q=!0;a.r=!0;a.Ca()}function N(){this.p=this.m=null;this.r=this.q=!1}function xb(){}xb.prototype=Error.prototype;N.prototype=new xb;
N.prototype.constructor=N;function yb(){}yb.prototype=N.prototype;N.prototype.S=function(){return this.m};N.prototype.Ca=function(){"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)};N.prototype.k=function(){var a=ha(this),b=this.S();return null===b?a:a+": "+b};N.prototype.l=function(){return z.prototype.l.call(this)};Object.defineProperty(N.prototype,"message",{get:function(){var a=this.S();return null===a?"":a},configurable:!0});
Object.defineProperty(N.prototype,"name",{get:function(){return ha(this)},configurable:!0});N.prototype.toString=function(){return this.k()};
function zb(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var d=(32+aa(1E9)|0)-(0!==b?aa(b):32+aa(a)|0)|0,c=d,e=0===(32&c)?1E9<<c:0;c=0===(32&c)?5E8>>>(31-c|0)|0|0<<c:1E9<<c;var g=a,f=b;for(a=b=0;0<=d&&0!==(-2097152&f);){var k=g,p=f,t=e,w=c;if(p===w?(-2147483648^k)>=(-2147483648^t):(-2147483648^p)>=(-2147483648^w))k=f,p=c,f=g-e|0,k=(-2147483648^f)>(-2147483648^g)?-1+(k-p|0)|0:k-p|0,g=f,f=k,32>d?b|=1<<d:a|=1<<d;d=-1+d|0;k=c>>>1|0;e=e>>>1|0|c<<31;c=k}d=f;if(0===d?-1147483648<=(-2147483648^
g):-2147483648<=(-2147483648^d))d=4294967296*f+ +(g>>>0),g=d/1E9,e=g/4294967296|0,c=b,b=g=c+(g|0)|0,a=(-2147483648^g)<(-2147483648^c)?1+(a+e|0)|0:a+e|0,g=d%1E9|0;d=""+g;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(d.length|0)+d}return b}function Ab(){this.Q=0}Ab.prototype=new v;Ab.prototype.constructor=Ab;Ab.prototype.$classData=u({fb:0},"org.scalajs.linker.runtime.RuntimeLong$",{fb:1,a:1,c:1});var Bb=void 0;function Ta(){Bb||(Bb=new Ab);return Bb}function Cb(){this.L=!1;this.M=null}
Cb.prototype=new v;Cb.prototype.constructor=Cb;Cb.prototype.k=function(){return"LazyRef "+(this.L?"of: "+this.M:"thunk")};Cb.prototype.$classData=u({Lb:0},"scala.runtime.LazyRef",{Lb:1,a:1,c:1});function Db(){this.la=0;Eb=this;this.la=q("Seq");q("Map");q("Set")}Db.prototype=new ab;Db.prototype.constructor=Db;Db.prototype.$classData=u({tb:0},"scala.util.hashing.MurmurHash3$",{tb:1,Xb:1,a:1});var Eb=void 0;function cb(){Eb||(Eb=new Db);return Eb}
function O(a,b,d,c,e,g,f,k,p){this.xa=0;this.E=null;this.ya=a;this.Ta=b;this.Sa=d;this.Va=c;this.Ua=e;this.N=g;this.Wa=f;this.Xa=k;this.wa=p;this.E=J();this.xa=(c<e?c:e)/(2*a.h)}O.prototype=new v;O.prototype.constructor=O;var Fb=u({Ra:0},"scalajs.fun.gravity.Gravity$Runner$1",{Ra:1,a:1,Rb:1});O.prototype.$classData=Fb;function Gb(){this.d=null;this.h=0;var a=new G(new M(0,45E9),new M(3E4,0),2.999E30,5E9),b=new M(0,-45E9),d=new M(-3E4,0);this.d=m(y(H),[a,new G(b,d,2.999E30,5E9)]);this.h=8E10}
Gb.prototype=new mb;Gb.prototype.constructor=Gb;Gb.prototype.$classData=u({$a:0},"scalajs.fun.gravity.universe1$",{$a:1,P:1,a:1});var Hb=void 0;function Ib(){this.d=null;this.h=0;var a=new G(new M(0,45E9),new M(3E4,0),2.999E30,5E9),b=new G(new M(0,-45E9),new M(-3E4,0),2.999E30,5E9),d=new M(0,0),c=new M(500,0);this.d=m(y(H),[a,b,new G(d,c,6.97E24,2E9)]);this.h=8E10}Ib.prototype=new mb;Ib.prototype.constructor=Ib;Ib.prototype.$classData=u({ab:0},"scalajs.fun.gravity.universe2$",{ab:1,P:1,a:1});
var Jb=void 0;function Kb(){this.d=null;this.h=0;var a=new G(new M(0,45E9),new M(1E4,0),1.5E30,5E9),b=new M(0,-45E9),d=new M(-1E4,0);this.d=m(y(H),[a,new G(b,d,1.5E30,5E9)]);this.h=1E11}Kb.prototype=new mb;Kb.prototype.constructor=Kb;Kb.prototype.$classData=u({bb:0},"scalajs.fun.gravity.universe3$",{bb:1,P:1,a:1});var Lb=void 0;
function Mb(){this.d=null;this.h=0;var a=new G(new M(-35E9,0),new M(0,1400),3E28,5E9),b=new G(new M(-1E10,0),new M(0,15E3),3E28,5E9),d=new G(new M(1E10,0),new M(0,-15E3),3E28,5E9),c=new M(35E9,0),e=new M(0,-1400);this.d=m(y(H),[a,b,d,new G(c,e,3E28,5E9)]);this.h=16E10}Mb.prototype=new mb;Mb.prototype.constructor=Mb;Mb.prototype.$classData=u({cb:0},"scalajs.fun.gravity.universe4$",{cb:1,P:1,a:1});var Nb=void 0;
function Ob(){this.d=null;this.h=0;var a=new G(new M(-35E9,0),new M(0,1400),3E28,5E9),b=new G(new M(-1E10,0),new M(0,16450),3E28,5E9),d=new G(new M(1E10,0),new M(0,-16450),3E28,5E9),c=new M(35E9,0),e=new M(0,-1400);this.d=m(y(H),[a,b,d,new G(c,e,3E28,5E9)]);this.h=16E10}Ob.prototype=new mb;Ob.prototype.constructor=Ob;Ob.prototype.$classData=u({db:0},"scalajs.fun.gravity.universe5$",{db:1,P:1,a:1});var Pb=void 0;function Qb(){this.p=this.m=null;this.r=this.q=!1}Qb.prototype=new yb;
Qb.prototype.constructor=Qb;function Rb(){}Rb.prototype=Qb.prototype;function Sb(){this.Z=null;Tb=this;this.Z=new P}Sb.prototype=new v;Sb.prototype.constructor=Sb;Sb.prototype.$classData=u({Db:0},"scala.collection.Iterator$",{Db:1,a:1,bc:1,c:1});var Tb=void 0;function Ub(){Tb||(Tb=new Sb);return Tb}function sb(){this.p=this.m=null;this.r=this.q=!1}sb.prototype=new Rb;sb.prototype.constructor=sb;function Vb(){}Vb.prototype=sb.prototype;
sb.prototype.$classData=u({D:0},"java.lang.RuntimeException",{D:1,G:1,I:1,a:1,c:1});function q(a){for(var b=0,d=1,c=-1+(a.length|0)|0;0<=c;)b=b+l(65535&(a.charCodeAt(c)|0),d)|0,d=l(31,d),c=-1+c|0;return b}var Wb=u({gb:0},"java.lang.String",{gb:1,a:1,c:1,ib:1,Ea:1},function(a){return"string"===typeof a});function Q(){this.e=""}Q.prototype=new v;Q.prototype.constructor=Q;Q.prototype.k=function(){return this.e};Q.prototype.s=function(){return this.e.length|0};
Q.prototype.$classData=u({mb:0},"java.lang.StringBuilder",{mb:1,a:1,Ea:1,Ub:1,c:1});function n(a,b){this.A=a;this.z=b}n.prototype=new wb;n.prototype.constructor=n;n.prototype.l=function(){return this.A^this.z};n.prototype.k=function(){Ta();var a=this.A,b=this.z;return b===a>>31?""+a:0>b?"-"+zb(-a|0,0!==a?~b:-b|0):zb(a,b)};n.prototype.$classData=u({eb:0},"org.scalajs.linker.runtime.RuntimeLong",{eb:1,Vb:1,a:1,c:1,ib:1});function R(){}R.prototype=new v;R.prototype.constructor=R;function Xb(){}
Xb.prototype=R.prototype;R.prototype.F=function(){return this};R.prototype.C=function(){return!this.i()};R.prototype.k=function(){return"\x3citerator\x3e"};R.prototype.za=function(a,b,d,c){return Pa(this,a,b,d,c)};function S(a){this.p=this.m=null;this.r=this.q=!1;tb(this,a)}S.prototype=new Vb;S.prototype.constructor=S;S.prototype.$classData=u({kb:0},"java.lang.IndexOutOfBoundsException",{kb:1,D:1,G:1,I:1,a:1,c:1});function fb(){this.p=this.m=null;this.r=this.q=!1;tb(this,null)}fb.prototype=new Vb;
fb.prototype.constructor=fb;fb.prototype.$classData=u({lb:0},"java.lang.NullPointerException",{lb:1,D:1,G:1,I:1,a:1,c:1});function Yb(a){this.p=this.m=null;this.r=this.q=!1;tb(this,a)}Yb.prototype=new Vb;Yb.prototype.constructor=Yb;Yb.prototype.$classData=u({nb:0},"java.util.NoSuchElementException",{nb:1,D:1,G:1,I:1,a:1,c:1});function L(a){this.p=this.m=null;this.r=this.q=!1;this.Ja=null;this.ka=!1;this.W=a;tb(this,null)}L.prototype=new Vb;L.prototype.constructor=L;
L.prototype.S=function(){if(!this.ka&&!this.ka){if(null===this.W)var a="null";else try{a=ia(this.W)+" (of class "+ha(this.W)+")"}catch(b){if(Xa||(Xa=new D),null!==(b instanceof N?b:new ub(b)))a="an instance of class "+ha(this.W);else throw b;}this.Ja=a;this.ka=!0}return this.Ja};L.prototype.$classData=u({ob:0},"scala.MatchError",{ob:1,D:1,G:1,I:1,a:1,c:1});function Zb(){}Zb.prototype=new v;Zb.prototype.constructor=Zb;function $b(){}$b.prototype=Zb.prototype;
Zb.prototype.C=function(){return this===J()};Zb.prototype.F=function(){if(this.C())return Ub().Z;Ub();var a=this.Da();return new T(a)};function P(){}P.prototype=new Xb;P.prototype.constructor=P;P.prototype.i=function(){return!1};P.prototype.j=function(){throw new Yb("next on empty iterator");};P.prototype.$classData=u({Eb:0},"scala.collection.Iterator$$anon$19",{Eb:1,ma:1,a:1,oa:1,w:1,K:1});function T(a){this.Gb=a;this.pa=!1}T.prototype=new Xb;T.prototype.constructor=T;T.prototype.i=function(){return!this.pa};
T.prototype.j=function(){if(this.pa)return Ub().Z.j();this.pa=!0;return this.Gb};T.prototype.$classData=u({Fb:0},"scala.collection.Iterator$$anon$20",{Fb:1,ma:1,a:1,oa:1,w:1,K:1});function U(a){this.La=0;this.Ob=a;this.aa=0;this.La=a.U()}U.prototype=new Xb;U.prototype.constructor=U;U.prototype.i=function(){return this.aa<this.La};U.prototype.j=function(){var a=this.Ob.V(this.aa);this.aa=1+this.aa|0;return a};
U.prototype.$classData=u({Nb:0},"scala.runtime.ScalaRunTime$$anon$1",{Nb:1,ma:1,a:1,oa:1,w:1,K:1});function ac(){}ac.prototype=new $b;ac.prototype.constructor=ac;h=ac.prototype;h.J=function(){return"None"};h.U=function(){return 0};h.V=function(a){C();throw new S(""+a);};h.l=function(){return 2433880};h.k=function(){return"None"};h.Da=function(){throw new Yb("None.get");};h.$classData=u({pb:0},"scala.None$",{pb:1,qb:1,a:1,w:1,Ka:1,ja:1,c:1});var bc=void 0;function J(){bc||(bc=new ac);return bc}
function K(a){this.X=a}K.prototype=new $b;K.prototype.constructor=K;h=K.prototype;h.Da=function(){return this.X};h.J=function(){return"Some"};h.U=function(){return 1};h.V=function(a){if(0===a)a=this.X;else throw C(),new S(""+a);return a};h.l=function(){return bb(this)};h.k=function(){Ra||(Ra=new Qa);var a=new U(this),b=this.J()+"(";return a.C()?""+b+")":a.za(cc(),b,",",")").x.e};h.$classData=u({rb:0},"scala.Some",{rb:1,qb:1,a:1,w:1,Ka:1,ja:1,c:1});function dc(){}dc.prototype=new v;
dc.prototype.constructor=dc;function ec(){}ec.prototype=dc.prototype;dc.prototype.za=function(a,b,d,c){return Pa(this,a,b,d,c)};function V(a){this.Y=0;this.zb=a;this.na=0;this.Y=a.s()}V.prototype=new Xb;V.prototype.constructor=V;V.prototype.i=function(){return 0<this.Y};V.prototype.j=function(){if(this.i()){var a=this.zb.o(this.na);this.na=1+this.na|0;this.Y=-1+this.Y|0;return a}return Ub().Z.j()};
V.prototype.$classData=u({yb:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{yb:1,ma:1,a:1,oa:1,w:1,K:1,c:1});function ub(a){this.p=this.m=null;this.r=this.q=!1;this.qa=a;tb(this,null)}ub.prototype=new Vb;ub.prototype.constructor=ub;h=ub.prototype;h.S=function(){return ia(this.qa)};h.Ca=function(){};h.J=function(){return"JavaScriptException"};h.U=function(){return 1};h.V=function(a){if(0===a)a=this.qa;else throw C(),new S(""+a);return a};h.l=function(){return bb(this)};
h.$classData=u({Jb:0},"scala.scalajs.js.JavaScriptException",{Jb:1,D:1,G:1,I:1,a:1,c:1,Ka:1,ja:1});function fc(){}fc.prototype=new ec;fc.prototype.constructor=fc;function gc(){}gc.prototype=fc.prototype;fc.prototype.k=function(){return"IndexedSeqView(\x3cnot computed\x3e)"};function hc(){}hc.prototype=new ec;hc.prototype.constructor=hc;function ic(){}ic.prototype=hc.prototype;
hc.prototype.l=function(){var a=cb();if(this&&this.$classData&&this.$classData.B.vb)a:{var b=a.la;a=this.s();switch(a){case 0:a=F(b^0);break a;case 1:a=b;b=this.o(0);a=F(E(a,B(C(),b))^1);break a;default:var d=this.o(0),c=B(C(),d);d=b=E(b,c);var e=this.o(1);e=B(C(),e);var g=e-c|0;for(c=2;c<a;){b=E(b,e);var f=this.o(c);f=B(C(),f);if(g!==(f-e|0)){b=E(b,f);for(c=1+c|0;c<a;)d=this.o(c),b=E(b,B(C(),d)),c=1+c|0;a=F(b^a);break a}e=f;c=1+c|0}a=F(E(E(d,g),e))}}else a:if(b=a.la,a=this.F(),a.i())if(d=a.j(),a.i()){c=
a.j();g=B(C(),d);d=b=E(b,g);e=B(C(),c);g=e-g|0;for(c=2;a.i();){b=E(b,e);f=a.j();f=B(C(),f);if(g!==(f-e|0)){b=E(b,f);for(c=1+c|0;a.i();)d=a.j(),b=E(b,B(C(),d)),c=1+c|0;a=F(b^c);break a}e=f;c=1+c|0}a=F(E(E(d,g),e))}else a=F(E(b,B(C(),d))^1);else a=F(b^0);return a};hc.prototype.C=function(){return 0===this.Ia(0)};function jc(){}jc.prototype=new gc;jc.prototype.constructor=jc;function kc(){}kc.prototype=jc.prototype;function W(){this.$=null}W.prototype=new kc;W.prototype.constructor=W;
function lc(){}lc.prototype=W.prototype;W.prototype.o=function(a){return this.$.o(a)};W.prototype.s=function(){return this.$.s()};W.prototype.C=function(){return this.$.C()};function X(a){this.$=a}X.prototype=new lc;X.prototype.constructor=X;X.prototype.F=function(){return new V(this)};X.prototype.Ia=function(a){var b=this.s();return b===a?0:b<a?-1:1};X.prototype.$classData=u({xb:0},"scala.collection.IndexedSeqView$Id",{xb:1,ec:1,Zb:1,$b:1,ub:1,a:1,Ab:1,w:1,Cb:1,K:1,Bb:1,fc:1,c:1,dc:1,Hb:1,ac:1,wb:1});
function mc(){}mc.prototype=new ic;mc.prototype.constructor=mc;function nc(){}nc.prototype=mc.prototype;function cc(){var a=new oc;a.x=new Q;return a}function oc(){this.x=null}oc.prototype=new nc;oc.prototype.constructor=oc;h=oc.prototype;h.F=function(){var a=new X(this);return new V(a)};h.Ia=function(a){var b=this.x.s();return b===a?0:b<a?-1:1};h.s=function(){return this.x.s()};h.k=function(){return this.x.e};h.o=function(a){return new da(65535&(this.x.e.charCodeAt(a)|0))};
h.$classData=u({Ib:0},"scala.collection.mutable.StringBuilder",{Ib:1,gc:1,Yb:1,ub:1,a:1,Ab:1,w:1,Cb:1,K:1,Bb:1,cc:1,Wb:1,Qb:1,Hb:1,ja:1,pc:1,nc:1,qc:1,jc:1,hb:1,oc:1,hc:1,kc:1,ic:1,lc:1,vb:1,wb:1,mc:1,Ea:1,c:1});ba=new n(0,0);m(y(Wb),[]);hb||(hb=new I);var pc=new Cb,qc=A().getElementById("canvas"),rc=qc.getContext("2d"),sc=new db(rc),Y=na(.8*+Ma(Na()).innerWidth),Z=na(.8*+Ma(Na()).innerHeight);qc.width=Y;qc.height=Z;var tc=Y/2|0,xc=Z/2|0,yc=y(Fb);Hb||(Hb=new Gb);
var zc=new O(Hb,3600,100,Y,Z,rc,tc,xc,sc);Jb||(Jb=new Ib);var Ac=new O(Jb,3600,100,Y,Z,rc,tc,xc,sc);Lb||(Lb=new Kb);var Bc=new O(Lb,5E3,200,Y,Z,rc,tc,xc,sc);Nb||(Nb=new Mb);var Cc=new O(Nb,25E3,500,Y,Z,rc,tc,xc,sc);Pb||(Pb=new Ob);var Dc=m(yc,[zc,Ac,Bc,Cc,new O(Pb,25E3,500,Y,Z,rc,tc,xc,sc)]);
(function(a,b){var d=A().createElement("label");d.innerText="Choose one universe: ";d.htmlFor="universes";var c=A().createElement("select");c.title="select one universe to simulate";c.id="universes";var e=a.b.length,g=-1+e|0;if(!(0>=e))for(e=0;;){var f=e,k=A().createElement("option");f="Universe "+f;k.value=f;k.innerText=f;c.appendChild(k);if(e===g)break;e=1+e|0}c.onchange=function(p,t,w){return function(){hb||(hb=new I);var x=p.selectedIndex|0;ib(t.L?t.M:eb(t,w),x)}}(c,b,a);a=A().createElement("h3");
a.innerText="Gravity";b=A().getElementById("controls");b.appendChild(a);b.appendChild(d);b.appendChild(c)})(Dc,pc);ib(pc.L?pc.M:eb(pc,Dc),0);
}).call(this);
//# sourceMappingURL=scalajsfun-opt.js.map
