(function(){
'use strict';var k;Object.freeze({assumingES6:!1,productionMode:!0,linkerVersion:"1.0.1",fileLevelThis:this});var l=Math.imul||function(a,b){var d=a&65535,c=b&65535;return d*c+((a>>>16)*c+d*(b>>>16)<<16>>>0)|0},aa=Math.clz32||function(a){if(0===a)return 32;var b=1;0===(a&-65536)&&(a<<=16,b+=16);0===(a&-16777216)&&(a<<=8,b+=8);0===(a&-268435456)&&(a<<=4,b+=4);0===(a&-1073741824)&&(a<<=2,b+=2);return b+(a>>31)},ba;function ca(a){for(var b in a)return b}function da(a){this.Ba=a}
da.prototype.toString=function(){return String.fromCharCode(this.Ba)};function m(a,b){return new a.ga(b)}var fa=function ea(a,b,d){var e=new a.ga(b[d]);if(d<b.length-1){a=a.Ca;d+=1;for(var f=e.b,g=0;g<f.length;g++)f[g]=ea(a,b,d)}return e};
function ha(a){switch(typeof a){case "string":return"java.lang.String";case "number":return"number"===typeof a&&(a|0)===a&&1/a!==1/-0?a<<24>>24===a?"java.lang.Byte":a<<16>>16===a?"java.lang.Short":"java.lang.Integer":"java.lang.Float";case "boolean":return"java.lang.Boolean";case "undefined":return"java.lang.Void";default:return null===a?a.Sb():a instanceof n?"java.lang.Long":a instanceof da?"java.lang.Character":a&&a.$classData?a.$classData.name:null.Tb()}}
function ia(a){return void 0===a?"undefined":a.toString()}function ja(a){switch(typeof a){case "string":return q(a);case "number":return a=+a,ka(la(),a);case "boolean":return a?1231:1237;case "undefined":return 0;default:return a&&a.$classData||null===a?a.m():a instanceof da?null===a?0:a.Ba:ma(a)}}function na(a){return 2147483647<a?2147483647:-2147483648>a?-2147483648:a|0}
var oa=0,pa="undefined"!==typeof WeakMap?new WeakMap:null,ma=null!==pa?function(a){switch(typeof a){case "string":case "number":case "bigint":case "boolean":case "undefined":return ja(a);default:if(null===a)return 0;var b=pa.get(a);void 0===b&&(oa=b=oa+1|0,pa.set(a,b));return b}}:function(a){switch(typeof a){case "string":case "number":case "bigint":case "boolean":case "undefined":return ja(a);default:if(a&&a.$classData){var b=a.$idHashCode$0;if(void 0!==b)return b;if(Object.isSealed(a))return 42;
oa=b=oa+1|0;return a.$idHashCode$0=b}null===a?0:42}};function qa(){this.ga=void 0;this.f=this.Ca=this.C=null;this.g=0;this.sa=null;this.R="";this.ia=this.fa=void 0;this.name="";this.isJSClass=this.isArrayClass=this.isInterface=this.isPrimitive=!1;this.isInstance=void 0}function r(a,b,d,c){var e=new qa;e.C={};e.sa=a;e.R=b;e.ia=c;e.name=d;e.isPrimitive=!0;e.isInstance=function(){return!1};return e}
function t(a,b,d,c,e){var f=new qa,g=ca(a);f.C=d;f.R="L"+b+";";f.ia=e||function(h,p){return!!(h&&h.$classData&&h.$classData.g===p&&h.$classData.f.C[g])};f.name=b;f.isInterface=!1;f.isInstance=c||function(h){return!!(h&&h.$classData&&h.$classData.C[g])};return f}
function ra(a){function b(h){if("number"===typeof h){this.b=Array(h);for(var p=0;p<h;p++)this.b[p]=c}else this.b=h}var d=new qa,c="longZero"===a.sa?ba:a.sa;b.prototype=new v;b.prototype.constructor=b;b.prototype.$classData=d;var e="["+a.R,f=a.f||a,g=a.g+1;d.ga=b;d.C={a:1,ib:1,c:1};d.Ca=a;d.f=f;d.g=g;d.R=e;d.name=e;d.isArrayClass=!0;d.isInstance=function(h){return f.ia(h,g)};return d}function y(a){a.fa||(a.fa=ra(a));return a.fa}
function sa(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==ta)}function ua(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==xa)}function ya(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==za)}function Aa(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Ba)}function Ca(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Da)}
function Ea(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Fa)}function Ga(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Ha)}function Ia(a,b){return!(!a||!a.$classData||a.$classData.g!==b||a.$classData.f!==Ja)}var ta=r(!1,"Z","boolean",sa),xa=r(0,"C","char",ua),za=r(0,"B","byte",ya),Ba=r(0,"S","short",Aa),Da=r(0,"I","int",Ca),Fa=r("longZero","J","long",Ea),Ha=r(0,"F","float",Ga),Ja=r(0,"D","double",Ia);function z(){}function v(){}v.prototype=z.prototype;
z.prototype.m=function(){return ma(this)};z.prototype.k=function(){var a=ha(this),b=this.m();return a+"@"+(+(b>>>0)).toString(16)};z.prototype.toString=function(){return this.k()};z.prototype.$classData=t({a:0},"java.lang.Object",{a:1},function(a){return null!==a},function(a,b){if(a=a&&a.$classData){var d=a.g||0;return!(d<b)&&(d>b||!a.f.isPrimitive)}return!1});
function Ka(){this.v=!1;this.Ga=this.T=this.J=null;this.ja=!1;this.Ia=this.Ha=0;La=this;this.J=(this.v="undefined"!==typeof ArrayBuffer&&"undefined"!==typeof Int32Array&&"undefined"!==typeof Float32Array&&"undefined"!==typeof Float64Array)?new ArrayBuffer(8):null;this.T=this.v?new Int32Array(this.J,0,2):null;this.v&&new Float32Array(this.J,0,2);this.Ga=this.v?new Float64Array(this.J,0,1):null;if(this.v)this.T[0]=16909060,a=1===((new Int8Array(this.J,0,8))[0]|0);else var a=!0;this.Ha=(this.ja=a)?0:
1;this.Ia=this.ja?1:0}Ka.prototype=new v;Ka.prototype.constructor=Ka;
function ka(a,b){var d=b|0;if(d===b&&-Infinity!==1/b)return d;if(a.v)a.Ga[0]=b,a=new n(a.T[a.Ia]|0,a.T[a.Ha]|0);else{if(b!==b)a=!1,b=2047,d=+Math.pow(2,51);else if(Infinity===b||-Infinity===b)a=0>b,b=2047,d=0;else if(0===b)a=-Infinity===1/b,d=b=0;else{var c=(a=0>b)?-b:b;if(c>=+Math.pow(2,-1022)){d=+Math.pow(2,52);b=+Math.floor(+Math.log(c)/.6931471805599453)|0;1023<b&&(b=1023);var e=+Math.pow(2,b);e>c&&(b=-1+b|0,e/=2);e=c/e*d;c=+Math.floor(e);e-=c;c=.5>e?c:.5<e?1+c:0!==c%2?1+c:c;2<=c/d&&(b=1+b|0,
c=1);1023<b?(b=2047,c=0):(b=1023+b|0,c-=d);d=c}else b=c/+Math.pow(2,-1074),d=+Math.floor(b),c=b-d,b=0,d=.5>c?d:.5<c?1+d:0!==d%2?1+d:d}a=new n(d|0,(a?-2147483648:0)|b<<20|d/4294967296|0)}return a.B^a.A}Ka.prototype.$classData=t({kb:0},"java.lang.FloatingPointBits$",{kb:1,a:1});var La=void 0;function la(){La||(La=new Ka);return La}function Ma(){this.ta=this.ua=null;this.q=0}Ma.prototype=new v;Ma.prototype.constructor=Ma;
function Na(a){0===(33554432&a.q)&&0===(33554432&a.q)&&(a.ua=window,a.q|=33554432);return a.ua}function Oa(){var a=Pa();0===(67108864&a.q)&&0===(67108864&a.q)&&(a.ta=Na(a).document,a.q|=67108864);return a.ta}Ma.prototype.$classData=t({Na:0},"org.scalajs.dom.package$",{Na:1,a:1});var Sa=void 0;function Pa(){Sa||(Sa=new Ma);return Sa}
function Ta(a,b,d,c,e){var f=b.y;0!==(d.length|0)&&(f.e=""+f.e+d);a=a.I();if(a.i())for(d=a.j(),f.e=""+f.e+d;a.i();)f.e=""+f.e+c,d=a.j(),f.e=""+f.e+d;0!==(e.length|0)&&(f.e=""+f.e+e);return b}function Ua(){}Ua.prototype=new v;Ua.prototype.constructor=Ua;Ua.prototype.$classData=t({Nb:0},"scala.runtime.ScalaRunTime$",{Nb:1,a:1});var Va=void 0;function Wa(){}Wa.prototype=new v;Wa.prototype.constructor=Wa;
function A(a,b){if(null===b)return 0;if("number"===typeof b){a=+b;b=na(a);if(b===a)a=b;else{b=Xa();if(-9223372036854775808>a){b.Q=-2147483648;var d=0}else if(0x7fffffffffffffff<=a)b.Q=2147483647,d=-1;else{d=a|0;var c=a/4294967296|0;b.Q=0>a&&0!==d?-1+c|0:c}b=b.Q;Xa();a=(0>b?-(4294967296*+((0!==d?~b:-b|0)>>>0)+ +((-d|0)>>>0)):4294967296*b+ +(d>>>0))===a?d^b:ka(la(),a)}return a}return b instanceof n?(a=null===b?ba:b,b=new n(a.B,a.A),a=b.B,b=b.A,b===a>>31?a:a^b):ja(b)}
Wa.prototype.$classData=t({Qb:0},"scala.runtime.Statics$",{Qb:1,a:1});var Ya=void 0;function B(){Ya||(Ya=new Wa);return Ya}function C(){}C.prototype=new v;C.prototype.constructor=C;C.prototype.$classData=t({Lb:0},"scala.scalajs.runtime.package$",{Lb:1,a:1});var Za=void 0;function $a(){}$a.prototype=new v;$a.prototype.constructor=$a;$a.prototype.$classData=t({tb:0},"scala.sys.package$",{tb:1,a:1});var ab=void 0;function bb(){}bb.prototype=new v;bb.prototype.constructor=bb;function cb(){}
cb.prototype=bb.prototype;function D(a,b){b=l(-862048943,b);b=l(461845907,b<<15|b>>>17|0);a^=b;return-430675100+l(5,a<<13|a>>>19|0)|0}function E(a){a=l(-2048144789,a^(a>>>16|0));a=l(-1028477387,a^(a>>>13|0));return a^(a>>>16|0)}function db(a){eb();var b=a.U();if(0===b)return q(a.K());var d=D(-889275714,q(a.K()));for(var c=0;c<b;){var e=a.V(c);d=D(d,A(B(),e));c=1+c|0}return E(d^b)}function F(a,b,d,c){this.z=a;this.ca=b;this.ba=d;this.Pa=c}F.prototype=new v;F.prototype.constructor=F;
F.prototype.ha=function(a){var b=a.da;b.beginPath();b.arc(this.z.t,this.z.u,this.Pa,0,6.283185307179586,!1);b.fillStyle="#00BB00";b.fill();b.lineWidth=2.5/a.va;b.strokeStyle="#0000FF";b.stroke()};var G=t({Oa:0},"scalajs.fun.gravity.Body",{Oa:1,a:1});F.prototype.$classData=G;function fb(a){this.da=a;this.va=1}fb.prototype=new v;fb.prototype.constructor=fb;fb.prototype.$classData=t({Qa:0},"scalajs.fun.gravity.Graphics2D",{Qa:1,a:1});
function gb(a,b){if(null===a)throw new hb;a.M?a=a.N:(b=new kb(b),a.N=b,a.M=!0,a=b);return a}function lb(){}lb.prototype=new v;lb.prototype.constructor=lb;lb.prototype.$classData=t({Ra:0},"scalajs.fun.gravity.Gravity$",{Ra:1,a:1});var mb=void 0;function nb(){mb||(mb=new lb);return mb}
function H(a,b,d,c,e,f,g,h){this.ya=this.xa=0;this.H=this.G=null;this.za=a;this.Ta=b;this.wa=c;this.Va=e;this.Ua=f;this.Wa=g;this.Xa=h;this.xa=(e<f?e:f)/(4*a.h);if(0===d)throw new ob("/ by zero");this.ya=1E3/d|0;this.G=c.da;this.H=I()}H.prototype=new v;H.prototype.constructor=H;
function pb(a){var b=a.H;if(I()===b)b=Na(Pa()).setInterval(function(d){return function(){d.G.setTransform(1,0,0,1,0,0);d.G.fillStyle="white";d.G.fillRect(0,0,d.Va,d.Ua);var c=d.za,e=d.Ta;var f=y(qb);f=fa(f,[c.d.b.length],0);var g=f.b.length,h=-1+g|0;if(!(0>=g))for(g=0;;){f.b[g]=new J(0,0);if(g===h)break;g=1+g|0}g=f.b.length;h=-1+g|0;if(!(0>=g))for(g=0;;){var p=g,u=f.b.length,w=-1+u|0;if(!(0>=u))for(u=0;;){var x=u;if(p!==x){var va=f.b,ib=p,jb=f.b[p],Qa=c.d.b[p];x=c.d.b[x];var wa=x.z;var Ra=Qa.z;wa=
new J(wa.t-Ra.t,wa.u-Ra.u);Ra=rb(wa);Qa=6.67E-11*Qa.ba*x.ba/+Math.pow(Ra,2);x=wa;if(0===rb(x))throw ab||(ab=new $a),Za||(Za=new C),c=new K,L(c,"Nul vector has no direction"),c=c instanceof M?c.ra:c,c;x=sb(x,1/rb(x));va[ib]=tb(jb,sb(x,Qa))}if(u===w)break;u=1+u|0}if(g===h)break;g=1+g|0}g=c.d.b.length;h=-1+g|0;if(!(0>=g))for(g=0;;){p=g;w=c.d.b[p];u=e;w.ca=tb(w.ca,sb(sb(f.b[p],1/w.ba),u));w.z=tb(w.z,sb(w.ca,u));if(g===h)break;g=1+g|0}d.G.translate(d.Wa,d.Xa);c=d.wa;e=d.xa;c.va=e;c.da.scale(e,e);d.za.ha(d.wa)}}(a),
a.ya)|0,a.H=new N(b);else if(!(b instanceof N))throw new O(b);}var ub=t({Sa:0},"scalajs.fun.gravity.Gravity$Runner$1",{Sa:1,a:1});H.prototype.$classData=ub;function kb(a){this.O=null;this.ea=a;this.O=I()}kb.prototype=new v;kb.prototype.constructor=kb;
function vb(a,b){var d=a.O;a:if(I()===d)pb(a.ea.b[b]),a.O=new N(b);else{if(d instanceof N){var c=d.X|0;if(b!==c){d=a.ea.b[c];c=d.H;if(I()!==c)if(c instanceof N)c=c.X|0,Na(Pa()).clearInterval(c),d.H=I();else throw new O(c);pb(a.ea.b[b]);a.O=new N(b);break a}}throw new O(d);}}kb.prototype.$classData=t({Ya:0},"scalajs.fun.gravity.Gravity$Running$1$",{Ya:1,a:1});function wb(){this.d=null;this.h=0}wb.prototype=new v;wb.prototype.constructor=wb;function xb(){}xb.prototype=wb.prototype;
wb.prototype.ha=function(a){var b=this.d;a=function(f,g){return function(h){h.ha(g)}}(this,a);var d=b.b.length,c=0;if(null!==b)for(;c<d;)a(b.b[c]),c=1+c|0;else if(Ca(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(Ia(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(Ea(b,1))for(;c<d;){var e=b.b[c];a(new n(e.B,e.A));c=1+c|0}else if(Ga(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(ua(b,1))for(;c<d;)a(new da(b.b[c])),c=1+c|0;else if(ya(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(Aa(b,1))for(;c<d;)a(b.b[c]),c=1+c|0;else if(sa(b,
1))for(;c<d;)a(b.b[c]),c=1+c|0;else throw new O(b);};function J(a,b){this.t=a;this.u=b}J.prototype=new v;J.prototype.constructor=J;function sb(a,b){return new J(a.t*b,a.u*b)}function tb(a,b){return new J(a.t+b.t,a.u+b.u)}function rb(a){a=+Math.pow(a.t,2)+ +Math.pow(a.u,2);return+Math.sqrt(a)}var qb=t({Za:0},"scalajs.fun.gravity.Vector",{Za:1,a:1});J.prototype.$classData=qb;function yb(){}yb.prototype=new v;yb.prototype.constructor=yb;function zb(){}zb.prototype=yb.prototype;
function L(a,b){a.l=b;a.n=null;a.o=!0;a.p=!0;a.Da()}function P(){this.n=this.l=null;this.p=this.o=!1}function Ab(){}Ab.prototype=Error.prototype;P.prototype=new Ab;P.prototype.constructor=P;function Bb(){}Bb.prototype=P.prototype;P.prototype.S=function(){return this.l};P.prototype.Da=function(){"[object Error]"!==Object.prototype.toString.call(this)&&void 0!==Error.captureStackTrace&&Error.captureStackTrace(this)};P.prototype.k=function(){var a=ha(this),b=this.S();return null===b?a:a+": "+b};
P.prototype.m=function(){return z.prototype.m.call(this)};Object.defineProperty(P.prototype,"message",{get:function(){var a=this.S();return null===a?"":a},configurable:!0});Object.defineProperty(P.prototype,"name",{get:function(){return ha(this)},configurable:!0});P.prototype.toString=function(){return this.k()};
function Cb(a,b){if(0===(-2097152&b))b=""+(4294967296*b+ +(a>>>0));else{var d=(32+aa(1E9)|0)-(0!==b?aa(b):32+aa(a)|0)|0,c=d,e=0===(32&c)?1E9<<c:0;c=0===(32&c)?5E8>>>(31-c|0)|0|0<<c:1E9<<c;var f=a,g=b;for(a=b=0;0<=d&&0!==(-2097152&g);){var h=f,p=g,u=e,w=c;if(p===w?(-2147483648^h)>=(-2147483648^u):(-2147483648^p)>=(-2147483648^w))h=g,p=c,g=f-e|0,h=(-2147483648^g)>(-2147483648^f)?-1+(h-p|0)|0:h-p|0,f=g,g=h,32>d?b|=1<<d:a|=1<<d;d=-1+d|0;h=c>>>1|0;e=e>>>1|0|c<<31;c=h}d=g;if(0===d?-1147483648<=(-2147483648^
f):-2147483648<=(-2147483648^d))d=4294967296*g+ +(f>>>0),f=d/1E9,e=f/4294967296|0,c=b,b=f=c+(f|0)|0,a=(-2147483648^f)<(-2147483648^c)?1+(a+e|0)|0:a+e|0,f=d%1E9|0;d=""+f;b=""+(4294967296*a+ +(b>>>0))+"000000000".substring(d.length|0)+d}return b}function Db(){this.Q=0}Db.prototype=new v;Db.prototype.constructor=Db;Db.prototype.$classData=t({fb:0},"org.scalajs.linker.runtime.RuntimeLong$",{fb:1,a:1,c:1});var Eb=void 0;function Xa(){Eb||(Eb=new Db);return Eb}function Fb(){this.M=!1;this.N=null}
Fb.prototype=new v;Fb.prototype.constructor=Fb;Fb.prototype.k=function(){return"LazyRef "+(this.M?"of: "+this.N:"thunk")};Fb.prototype.$classData=t({Mb:0},"scala.runtime.LazyRef",{Mb:1,a:1,c:1});function Gb(){this.ma=0;Hb=this;this.ma=q("Seq");q("Map");q("Set")}Gb.prototype=new cb;Gb.prototype.constructor=Gb;Gb.prototype.$classData=t({ub:0},"scala.util.hashing.MurmurHash3$",{ub:1,Xb:1,a:1});var Hb=void 0;function eb(){Hb||(Hb=new Gb);return Hb}
function Ib(){this.d=null;this.h=0;var a=new F(new J(0,45E9),new J(3E4,0),2.999E30,5E9),b=new J(0,-45E9),d=new J(-3E4,0);this.d=m(y(G),[a,new F(b,d,2.999E30,5E9)]);this.h=4E10}Ib.prototype=new xb;Ib.prototype.constructor=Ib;Ib.prototype.$classData=t({$a:0},"scalajs.fun.gravity.universe1$",{$a:1,P:1,a:1});var Jb=void 0;
function Kb(){this.d=null;this.h=0;var a=new F(new J(0,45E9),new J(3E4,0),2.999E30,5E9),b=new F(new J(0,-45E9),new J(-3E4,0),2.999E30,5E9),d=new J(0,0),c=new J(500,0);this.d=m(y(G),[a,b,new F(d,c,6.97E24,2E9)]);this.h=4E10}Kb.prototype=new xb;Kb.prototype.constructor=Kb;Kb.prototype.$classData=t({ab:0},"scalajs.fun.gravity.universe2$",{ab:1,P:1,a:1});var Lb=void 0;
function Mb(){this.d=null;this.h=0;var a=new F(new J(0,45E9),new J(1E4,0),1.5E30,5E9),b=new J(0,-45E9),d=new J(-1E4,0);this.d=m(y(G),[a,new F(b,d,1.5E30,5E9)]);this.h=5E10}Mb.prototype=new xb;Mb.prototype.constructor=Mb;Mb.prototype.$classData=t({bb:0},"scalajs.fun.gravity.universe3$",{bb:1,P:1,a:1});var Nb=void 0;
function Ob(){this.d=null;this.h=0;var a=new F(new J(-35E9,0),new J(0,1400),3E28,5E9),b=new F(new J(-1E10,0),new J(0,15E3),3E28,5E9),d=new F(new J(1E10,0),new J(0,-15E3),3E28,5E9),c=new J(35E9,0),e=new J(0,-1400);this.d=m(y(G),[a,b,d,new F(c,e,3E28,5E9)]);this.h=8E10}Ob.prototype=new xb;Ob.prototype.constructor=Ob;Ob.prototype.$classData=t({cb:0},"scalajs.fun.gravity.universe4$",{cb:1,P:1,a:1});var Pb=void 0;
function Qb(){this.d=null;this.h=0;var a=new F(new J(-35E9,0),new J(0,1400),3E28,5E9),b=new F(new J(-1E10,0),new J(0,16450),3E28,5E9),d=new F(new J(1E10,0),new J(0,-16450),3E28,5E9),c=new J(35E9,0),e=new J(0,-1400);this.d=m(y(G),[a,b,d,new F(c,e,3E28,5E9)]);this.h=8E10}Qb.prototype=new xb;Qb.prototype.constructor=Qb;Qb.prototype.$classData=t({db:0},"scalajs.fun.gravity.universe5$",{db:1,P:1,a:1});var Rb=void 0;function Sb(){this.n=this.l=null;this.p=this.o=!1}Sb.prototype=new Bb;
Sb.prototype.constructor=Sb;function Tb(){}Tb.prototype=Sb.prototype;function Ub(){this.Z=null;Vb=this;this.Z=new Q}Ub.prototype=new v;Ub.prototype.constructor=Ub;Ub.prototype.$classData=t({Eb:0},"scala.collection.Iterator$",{Eb:1,a:1,bc:1,c:1});var Vb=void 0;function Wb(){Vb||(Vb=new Ub);return Vb}function K(){this.n=this.l=null;this.p=this.o=!1}K.prototype=new Tb;K.prototype.constructor=K;function R(){}R.prototype=K.prototype;
K.prototype.$classData=t({w:0},"java.lang.RuntimeException",{w:1,E:1,F:1,a:1,c:1});function q(a){for(var b=0,d=1,c=-1+(a.length|0)|0;0<=c;)b=b+l(65535&(a.charCodeAt(c)|0),d)|0,d=l(31,d),c=-1+c|0;return b}var Xb=t({gb:0},"java.lang.String",{gb:1,a:1,c:1,jb:1,Fa:1},function(a){return"string"===typeof a});function S(){this.e=""}S.prototype=new v;S.prototype.constructor=S;S.prototype.k=function(){return this.e};S.prototype.s=function(){return this.e.length|0};
S.prototype.$classData=t({nb:0},"java.lang.StringBuilder",{nb:1,a:1,Fa:1,Ub:1,c:1});function n(a,b){this.B=a;this.A=b}n.prototype=new zb;n.prototype.constructor=n;n.prototype.m=function(){return this.B^this.A};n.prototype.k=function(){Xa();var a=this.B,b=this.A;return b===a>>31?""+a:0>b?"-"+Cb(-a|0,0!==a?~b:-b|0):Cb(a,b)};n.prototype.$classData=t({eb:0},"org.scalajs.linker.runtime.RuntimeLong",{eb:1,Vb:1,a:1,c:1,jb:1});function T(){}T.prototype=new v;T.prototype.constructor=T;function Yb(){}
Yb.prototype=T.prototype;T.prototype.I=function(){return this};T.prototype.D=function(){return!this.i()};T.prototype.k=function(){return"\x3citerator\x3e"};T.prototype.Aa=function(a,b,d,c){return Ta(this,a,b,d,c)};function ob(a){this.n=this.l=null;this.p=this.o=!1;L(this,a)}ob.prototype=new R;ob.prototype.constructor=ob;ob.prototype.$classData=t({hb:0},"java.lang.ArithmeticException",{hb:1,w:1,E:1,F:1,a:1,c:1});function U(a){this.n=this.l=null;this.p=this.o=!1;L(this,a)}U.prototype=new R;
U.prototype.constructor=U;U.prototype.$classData=t({lb:0},"java.lang.IndexOutOfBoundsException",{lb:1,w:1,E:1,F:1,a:1,c:1});function hb(){this.n=this.l=null;this.p=this.o=!1;L(this,null)}hb.prototype=new R;hb.prototype.constructor=hb;hb.prototype.$classData=t({mb:0},"java.lang.NullPointerException",{mb:1,w:1,E:1,F:1,a:1,c:1});function Zb(a){this.n=this.l=null;this.p=this.o=!1;L(this,a)}Zb.prototype=new R;Zb.prototype.constructor=Zb;
Zb.prototype.$classData=t({ob:0},"java.util.NoSuchElementException",{ob:1,w:1,E:1,F:1,a:1,c:1});function O(a){this.n=this.l=null;this.p=this.o=!1;this.Ka=null;this.la=!1;this.W=a;L(this,null)}O.prototype=new R;O.prototype.constructor=O;O.prototype.S=function(){if(!this.la&&!this.la){if(null===this.W)var a="null";else try{a=ia(this.W)+" (of class "+ha(this.W)+")"}catch(b){if(Za||(Za=new C),null!==(b instanceof P?b:new M(b)))a="an instance of class "+ha(this.W);else throw b;}this.Ka=a;this.la=!0}return this.Ka};
O.prototype.$classData=t({pb:0},"scala.MatchError",{pb:1,w:1,E:1,F:1,a:1,c:1});function $b(){}$b.prototype=new v;$b.prototype.constructor=$b;function ac(){}ac.prototype=$b.prototype;$b.prototype.D=function(){return this===I()};$b.prototype.I=function(){if(this.D())return Wb().Z;Wb();var a=this.Ea();return new V(a)};function Q(){}Q.prototype=new Yb;Q.prototype.constructor=Q;Q.prototype.i=function(){return!1};Q.prototype.j=function(){throw new Zb("next on empty iterator");};
Q.prototype.$classData=t({Fb:0},"scala.collection.Iterator$$anon$19",{Fb:1,na:1,a:1,pa:1,x:1,L:1});function V(a){this.Hb=a;this.qa=!1}V.prototype=new Yb;V.prototype.constructor=V;V.prototype.i=function(){return!this.qa};V.prototype.j=function(){if(this.qa)return Wb().Z.j();this.qa=!0;return this.Hb};V.prototype.$classData=t({Gb:0},"scala.collection.Iterator$$anon$20",{Gb:1,na:1,a:1,pa:1,x:1,L:1});function W(a){this.Ma=0;this.Pb=a;this.aa=0;this.Ma=a.U()}W.prototype=new Yb;
W.prototype.constructor=W;W.prototype.i=function(){return this.aa<this.Ma};W.prototype.j=function(){var a=this.Pb.V(this.aa);this.aa=1+this.aa|0;return a};W.prototype.$classData=t({Ob:0},"scala.runtime.ScalaRunTime$$anon$1",{Ob:1,na:1,a:1,pa:1,x:1,L:1});function bc(){}bc.prototype=new ac;bc.prototype.constructor=bc;k=bc.prototype;k.K=function(){return"None"};k.U=function(){return 0};k.V=function(a){B();throw new U(""+a);};k.m=function(){return 2433880};k.k=function(){return"None"};
k.Ea=function(){throw new Zb("None.get");};k.$classData=t({qb:0},"scala.None$",{qb:1,rb:1,a:1,x:1,La:1,ka:1,c:1});var cc=void 0;function I(){cc||(cc=new bc);return cc}function N(a){this.X=a}N.prototype=new ac;N.prototype.constructor=N;k=N.prototype;k.Ea=function(){return this.X};k.K=function(){return"Some"};k.U=function(){return 1};k.V=function(a){if(0===a)a=this.X;else throw B(),new U(""+a);return a};k.m=function(){return db(this)};
k.k=function(){Va||(Va=new Ua);var a=new W(this),b=this.K()+"(";return a.D()?""+b+")":a.Aa(dc(),b,",",")").y.e};k.$classData=t({sb:0},"scala.Some",{sb:1,rb:1,a:1,x:1,La:1,ka:1,c:1});function ec(){}ec.prototype=new v;ec.prototype.constructor=ec;function fc(){}fc.prototype=ec.prototype;ec.prototype.Aa=function(a,b,d,c){return Ta(this,a,b,d,c)};function X(a){this.Y=0;this.Ab=a;this.oa=0;this.Y=a.s()}X.prototype=new Yb;X.prototype.constructor=X;X.prototype.i=function(){return 0<this.Y};
X.prototype.j=function(){if(this.i()){var a=this.Ab.r(this.oa);this.oa=1+this.oa|0;this.Y=-1+this.Y|0;return a}return Wb().Z.j()};X.prototype.$classData=t({zb:0},"scala.collection.IndexedSeqView$IndexedSeqViewIterator",{zb:1,na:1,a:1,pa:1,x:1,L:1,c:1});function M(a){this.n=this.l=null;this.p=this.o=!1;this.ra=a;L(this,null)}M.prototype=new R;M.prototype.constructor=M;k=M.prototype;k.S=function(){return ia(this.ra)};k.Da=function(){};k.K=function(){return"JavaScriptException"};k.U=function(){return 1};
k.V=function(a){if(0===a)a=this.ra;else throw B(),new U(""+a);return a};k.m=function(){return db(this)};k.$classData=t({Kb:0},"scala.scalajs.js.JavaScriptException",{Kb:1,w:1,E:1,F:1,a:1,c:1,La:1,ka:1});function gc(){}gc.prototype=new fc;gc.prototype.constructor=gc;function hc(){}hc.prototype=gc.prototype;gc.prototype.k=function(){return"IndexedSeqView(\x3cnot computed\x3e)"};function ic(){}ic.prototype=new fc;ic.prototype.constructor=ic;function jc(){}jc.prototype=ic.prototype;
ic.prototype.m=function(){var a=eb();if(this&&this.$classData&&this.$classData.C.wb)a:{var b=a.ma;a=this.s();switch(a){case 0:a=E(b^0);break a;case 1:a=b;b=this.r(0);a=E(D(a,A(B(),b))^1);break a;default:var d=this.r(0),c=A(B(),d);d=b=D(b,c);var e=this.r(1);e=A(B(),e);var f=e-c|0;for(c=2;c<a;){b=D(b,e);var g=this.r(c);g=A(B(),g);if(f!==(g-e|0)){b=D(b,g);for(c=1+c|0;c<a;)d=this.r(c),b=D(b,A(B(),d)),c=1+c|0;a=E(b^a);break a}e=g;c=1+c|0}a=E(D(D(d,f),e))}}else a:if(b=a.ma,a=this.I(),a.i())if(d=a.j(),a.i()){c=
a.j();f=A(B(),d);d=b=D(b,f);e=A(B(),c);f=e-f|0;for(c=2;a.i();){b=D(b,e);g=a.j();g=A(B(),g);if(f!==(g-e|0)){b=D(b,g);for(c=1+c|0;a.i();)d=a.j(),b=D(b,A(B(),d)),c=1+c|0;a=E(b^c);break a}e=g;c=1+c|0}a=E(D(D(d,f),e))}else a=E(D(b,A(B(),d))^1);else a=E(b^0);return a};ic.prototype.D=function(){return 0===this.Ja(0)};function kc(){}kc.prototype=new hc;kc.prototype.constructor=kc;function lc(){}lc.prototype=kc.prototype;function Y(){this.$=null}Y.prototype=new lc;Y.prototype.constructor=Y;
function mc(){}mc.prototype=Y.prototype;Y.prototype.r=function(a){return this.$.r(a)};Y.prototype.s=function(){return this.$.s()};Y.prototype.D=function(){return this.$.D()};function Z(a){this.$=a}Z.prototype=new mc;Z.prototype.constructor=Z;Z.prototype.I=function(){return new X(this)};Z.prototype.Ja=function(a){var b=this.s();return b===a?0:b<a?-1:1};Z.prototype.$classData=t({yb:0},"scala.collection.IndexedSeqView$Id",{yb:1,ec:1,Zb:1,$b:1,vb:1,a:1,Bb:1,x:1,Db:1,L:1,Cb:1,fc:1,c:1,dc:1,Ib:1,ac:1,xb:1});
function nc(){}nc.prototype=new jc;nc.prototype.constructor=nc;function oc(){}oc.prototype=nc.prototype;function dc(){var a=new pc;a.y=new S;return a}function pc(){this.y=null}pc.prototype=new oc;pc.prototype.constructor=pc;k=pc.prototype;k.I=function(){var a=new Z(this);return new X(a)};k.Ja=function(a){var b=this.y.s();return b===a?0:b<a?-1:1};k.s=function(){return this.y.s()};k.k=function(){return this.y.e};k.r=function(a){return new da(65535&(this.y.e.charCodeAt(a)|0))};
k.$classData=t({Jb:0},"scala.collection.mutable.StringBuilder",{Jb:1,gc:1,Yb:1,vb:1,a:1,Bb:1,x:1,Db:1,L:1,Cb:1,cc:1,Wb:1,Rb:1,Ib:1,ka:1,pc:1,nc:1,qc:1,jc:1,ib:1,oc:1,hc:1,kc:1,ic:1,lc:1,wb:1,xb:1,mc:1,Fa:1,c:1});ba=new n(0,0);m(y(Xb),[]);
(function(){var a=new Fb,b=Oa().getElementById("canvas"),d=b.getContext("2d");d=new fb(d);var c=na(.85*+Na(Pa()).innerWidth),e=na(.85*+Na(Pa()).innerHeight);b.width=c;b.height=e;b=c/2;var f=e/2,g=y(ub);Jb||(Jb=new Ib);var h=new H(Jb,3600,100,d,c,e,b,f);Lb||(Lb=new Kb);var p=new H(Lb,3600,100,d,c,e,b,f);Nb||(Nb=new Mb);var u=new H(Nb,5E3,200,d,c,e,b,f);Pb||(Pb=new Ob);var w=new H(Pb,25E3,500,d,c,e,b,f);Rb||(Rb=new Qb);d=m(g,[h,p,u,w,new H(Rb,25E3,500,d,c,e,b,f)]);c=Oa().createElement("label");c.innerText=
"Choose an universe: ";c.htmlFor="universes";e=Oa().createElement("select");e.id="universes";f=d.b.length;b=-1+f|0;if(!(0>=f))for(f=0;;){h=f;g=Oa().createElement("option");h="Universe "+h;g.value=h;g.innerText=h;e.appendChild(g);if(f===b)break;f=1+f|0}e.onchange=function(x,va,ib){return function(){nb();var jb=x.selectedIndex|0;vb(va.M?va.N:gb(va,ib),jb)}}(e,a,d);b=Oa().getElementById("controls");b.appendChild(c);b.appendChild(e);vb(a.M?a.N:gb(a,d),0)})(nb());
}).call(this);
//# sourceMappingURL=scalajsfun-opt.js.map
